### PR TITLE
Try harder to cleanup only once

### PR DESCRIPTION
**Pull request by benclifford**
…once.

### CODE REVIEW

**Comment by benclifford** [comment]
I'm a little unsure what's happening in testing here:

On my laptop, running `pytest parsl/tests --basic`, I trigger the exception introduced by this patch, but in a situation that is unexpected to me: test_cleanup_behavior_221 fails with `Exception: attempt to clean up DFK when it has already been cleaned-up`. It doesn't fail when I run it from the commandline, or in CI. @annawoodard any ideas?

Also in one (but not both) of the travis builds, this timed out on `parsl/tests/test_swift.py` but ran successfully on a re-run. https://travis-ci.org/Parsl/parsl/jobs/381673923

**Comment by benclifford** [comment]
Also breaks `parsl/tests/test_bash_apps/test_basic.py` on my laptop

**Comment by annawoodard** [comment]
@benclifford I will have a look now

**Comment by annawoodard** [comment]
@benclifford running `pytest --basic` should work now, can you confirm?

The main change here is that I marked the cleanup test in question as `local` so that pytest won't try to interfere with it.

**Comment by annawoodard** [comment]
Note that unfortunately running on 08375ca does not seem to solve #271 for me:

```
(parsl_py36) [MacBook-Pro] ~/ci/parsl/parsl/tests >pytest --basic
========================================= test session starts =========================================
platform darwin -- Python 3.6.2, pytest-3.5.1, py-1.5.3, pluggy-0.6.0
rootdir: /Users/awoodard/ci/parsl/parsl/tests, inifile: pytest.ini
plugins: xdist-1.22.2, timeout-1.2.1, ordering-0.5, lazy-fixture-0.4.0, forked-0.2
collected 429 items / 8 skipped

test_aalst_patterns.py ssssssssssssssssssssssssss                                               [  6%]
test_docker_multisite.py s                                                                      [  6%]
test_factory.py ..                                                                              [  6%]
test_swift.py ...                                                                               [  7%]
test_thread_parallelism.py ss                                                                   [  7%]
[snip]
test_sites/test_local_threads_ipp.py ss                                                         [100%]
======================================= short test summary info =======================================
SKIP [2] /Users/awoodard/ci/parsl/parsl/tests/configs/midway_ipp.py:9: midway user_opts not configured {}
SKIP [2] /Users/awoodard/ci/parsl/parsl/tests/configs/local_threads_globus.py:9: globus user_opts not configured
SKIP [1] /Users/awoodard/ci/parsl/parsl/tests/configs/cooley_local_single_node.py:9: cooley user_opts not configured
SKIP [1] /Users/awoodard/ci/parsl/parsl/tests/configs/cori_ipp_multinode.py:20: cori user_opts not configured
[snip]
============================== 175 passed, 262 skipped in 504.91 seconds ==============================
2018-05-22 15:34:44 parsl.dataflow.strategy:178 [DEBUG]  Min:0 initBlocks:4 Max:10
2018-05-22 15:34:44 parsl.dataflow.strategy:178 [DEBUG]  Min:0 initBlocks:4 Max:10
2018-05-22 15:34:44 parsl.dataflow.strategy:155 [DEBUG]  Site:local_threads Status:STATIC
2018-05-22 15:34:44 parsl.dataflow.strategy:155 [DEBUG]  Site:local_threads Status:STATIC
Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "/Users/awoodard/ci/parsl/parsl/dataflow/dflow.py", line 547, in atexit_cleanup
    self.cleanup()
  File "/Users/awoodard/ci/parsl/parsl/dataflow/dflow.py", line 591, in cleanup
    executor.scale_in(len(job_ids))
  File "/Users/awoodard/ci/parsl/parsl/executors/ipp.py", line 243, in scale_in
    r = self.execution_provider.cancel(to_kill, *args, **kwargs)
  File "/Users/awoodard/software/anaconda3/envs/parsl_py36/lib/python3.6/site-packages/libsubmit-0.3.2-py3.6.egg/libsubmit/providers/local/local.py", line 240, in cancel
    os.killpg(os.getpgid(proc.pid), signal.SIGTERM)
ProcessLookupError: [Errno 3] No such process
```

**Pull request merged**
