### PR TITLE
draft CITATION.cff file

### PR DESCRIPTION
**Pull request by danielskatz**
# Description

Adding this to test a feature that could make it easier for others who use Parsl to cite it

I'm not sure about the authors - are we missing anyone?

## Type of change

Choose which options apply, and delete the ones which do not apply.

- Documentation update

### CODE REVIEW

**Comment by benclifford** [comment]
wrt authors list, is this different from the contributors list - eg pulling commit authors out, there are:

```
git log | grep ^Auth| sort | uniq| wc -l
78
```

78 distinct author addresses (with some duplicates, so more like human 70 commit authors)

**Comment by danielskatz** [comment]
> wrt authors list, is this different from the contributors list

Right - so we could ask
1. Should all contributors be recognized as authors?
2. Are there non-contributors who should be recognized as authors?
3. What's our criteria for authorship?

The list currently in this file is from our CodeMeta.json file (last updated for parsl 0.6.4), with @benclifford added manually

**Comment by danielskatz** [comment]
@benclifford - we decided to add everyone who has contributed other than typo-like fixes, and others who have made contributions to the project that are not captured in the repo.

How does this now look to you?

**Comment by benclifford** [comment]
@danielskatz I'm not super fussed about how the author list is compiled. The git repo already contains the level of contributor metadata that I'm interested in.

**Review by benclifford — APPROVED** [review]

**Pull request merged**
