### PR TITLE
set monitoring zmq channel linger options to 0 to prevent shutdown delay

### LINKED ISSUE #1438: 1 second workflow takes 31 seconds with monitoring enabled
**Describe the bug**
The below workflow takes 31 seconds to run with monitoring enabled. With monitoring disabled, it takes 1 second.

**To Reproduce**
Run this code with master = ea8333c3249fdf3b21691b7a66fb4e9c8ed37ec0

```
import parsl

from parsl.monitoring.monitoring import MonitoringHub
from parsl.configs.local_threads import config
from parsl.addresses import address_by_hostname

config.monitoring=MonitoringHub(
       hub_address=address_by_hostname(),
       hub_port=55055,
       resource_monitoring_interval=10,
   )

parsl.load(config)

@parsl.python_app()
def foo():
    return 7

print(foo().result())
```

```
time python md.py 
7

real    0m31.128s
user    0m1.000s
sys     0m0.260s
```

**Expected behavior**
The workflow should run much closer to the runtime with monitoring disabled:

```
time python md.py 
7

real    0m0.829s
user    0m0.692s
sys     0m0.124s
```

**Environment**
my laptop, python 3.7, parsl master ea8333c3249fdf3b21691b7a66fb4e9c8ed37ec0

### PR DESCRIPTION
**Pull request by ZhuozhaoLi**
As reported in #1438 , with monitoring enabled, it took 31s for a very short workflow.
This is because we recently changed the monitoring closing mechanism in PR #1403 .
But it took a long time for the `Hub` process to join because of the long zmq context termination.

This PR sets the zmq lingering option to 0, so the context will terminate immediately.

Fixes #1438

### CODE REVIEW

**Comment by benclifford** [comment]
From reading about LINGER, I think this means that:
 * there is a message that was taking 30 seconds to deliver that is now being discarded? 
or
 * LINGER was being set to 30 seconds somewhere
?

**Comment by benclifford** [comment]
In my laptop test of the code in #1438, this reduces the run time from 31s to 4s.

**Comment by ZhuozhaoLi** [comment]
> In my laptop test of the code in #1438, this reduces the run time from 31s to 4s.

This is because I put a timeout of 3s at the `Hub`, so that it has enough time receive all messages.

**Comment by ZhuozhaoLi** [comment]
> From reading about LINGER, I think this means that:
> 
> * there is a message that was taking 30 seconds to deliver that is now being discarded?
>   or
> * LINGER was being set to 30 seconds somewhere
>   ?

The `Hub` will never send messages, but will only receive messages. But upon the close, there should not be any messages coming in.

I think the default of linger is `-1`, which means infinite .
http://api.zeromq.org/2-1:zmq-setsockopt

**Comment by benclifford** [comment]
so where does the 30s come from? (rather than any other number)

**Comment by ZhuozhaoLi** [comment]
> so where does the 30s come from? (rather than any other number)

Removing the linger of `ic_channel` still leads to a run time of ~4s. So that is the problem of the `dfk_channel`. I do not see any monitoring message missing with linger set  to 0. 

Was trying to reproduce with a local zmq script, but unfortunately did not succeed. So I have not found out what happens here.

**Pull request merged**
