### PR TITLE
Remove last usage of `six` Python 2 compatibility layer

### PR DESCRIPTION
**Pull request by a-detiste**
https://wiki.debian.org/Python3-six-removal

### CODE REVIEW

**Comment by benclifford** [comment]
Removing `six` looks like a good thing to do.

I wonder if looks nicer to get rid of that `reraise` method entirely and fold it into the only place it is used, inside the `reraise` call of `RemoteExceptionWrapper`, and in that case I think at least one codepath can be eliminated:

```
def reraise(tp, value, tb=None):
    try:
        if value is None:

# I think value will never be none: a RemoteExceptionWrapper is always constructed from an exception.

            value = tp()
        if value.__traceback__ is not tb:
            raise value.with_traceback(tb)
        raise value
    finally:
        value = None
        tb = None
```

Administratively:
* please do not reformat code that is not related to the PR topic.
* this is failing in CI at the moment due to an unexpected dependency breakage - see PR https://github.com/Parsl/parsl/pull/3032 which I hope will be resolved today

**Comment by a-detiste** [comment]
mypy is not pleased

**Comment by a-detiste** [comment]
> please do not reformat code that is not related to the PR topic.

that was just a quick test to get past CI, I have reverted it

**Comment by benclifford** [comment]
I removed what I think is a no-op `finally` block, in this commit: https://github.com/Parsl/parsl/commit/ec6a18b4afc9395b23111b6a1d3e632e77a5430e - does that makes sense?


I was also interested in how this would change stack traces for users, as preserving the remote stack trace (i.e. in the user's remote code) is a pretty important part of this.

So I tried this against both `master` and PR #3033:

```
import parsl
from parsl.tests.configs.htex_local import fresh_config


@parsl.python_app
def a():
    def inner():
        raise RuntimeError("hello from benc")
    inner()


parsl.load(fresh_config())

a().result()
```

With `master`:

```
python backtrace.py 
Traceback (most recent call last):
  File "/home/benc/parsl/src/parsl/backtrace.py", line 14, in <module>
    a().result()
  File "/usr/local/lib/python3.11/concurrent/futures/_base.py", line 456, in result
    return self.__get_result()
           ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/concurrent/futures/_base.py", line 401, in __get_result
    raise self._exception
  File "/home/benc/parsl/src/parsl/parsl/dataflow/dflow.py", line 302, in handle_exec_update
    res = self._unwrap_remote_exception_wrapper(future)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/benc/parsl/src/parsl/parsl/dataflow/dflow.py", line 572, in _unwrap_remote_exception_wrapper
    result.reraise()
  File "/home/benc/parsl/src/parsl/parsl/app/errors.py", line 122, in reraise
    reraise(t, v, v.__traceback__)
  File "/home/benc/parsl/virtualenv-3.11/lib/python3.11/site-packages/six.py", line 719, in reraise
    raise value
  File "/home/benc/parsl/src/parsl/parsl/app/errors.py", line 145, in wrapper
    return func(*args, **kwargs)
^^^^^^^^^^^^^^^
  File "/home/benc/parsl/src/parsl/backtrace.py", line 9, in a
    inner()
      ^^^^^^
  File "/home/benc/parsl/src/parsl/backtrace.py", line 8, in inner
    raise RuntimeError("hello from benc")
  ^^^^^^^^^^^^^^^^^
RuntimeError: hello from benc
```

and with this PR #3033:


```
Traceback (most recent call last):
  File "/home/benc/parsl/src/parsl/backtrace.py", line 14, in <module>
    a().result()
  File "/usr/local/lib/python3.11/concurrent/futures/_base.py", line 456, in result
    return self.__get_result()
           ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/concurrent/futures/_base.py", line 401, in __get_result
    raise self._exception
  File "/home/benc/parsl/src/parsl/parsl/dataflow/dflow.py", line 302, in handle_exec_update
    res = self._unwrap_remote_exception_wrapper(future)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/benc/parsl/src/parsl/parsl/dataflow/dflow.py", line 572, in _unwrap_remote_exception_wrapper
    result.reraise()
  File "/home/benc/parsl/src/parsl/parsl/app/errors.py", line 118, in reraise
    raise v
  File "/home/benc/parsl/src/parsl/parsl/app/errors.py", line 141, in wrapper
    return func(*args, **kwargs)
^^^^^^^^^^^^^^^
  File "/home/benc/parsl/src/parsl/backtrace.py", line 9, in a
    inner()
      ^^^^^^
  File "/home/benc/parsl/src/parsl/backtrace.py", line 8, in inner
    raise RuntimeError("hello from benc")
  ^^^^^^^^^^^^^^^^^
RuntimeError: hello from benc
```

So this PR preserves the user bit of the stack trace (the last two frames) and removes one line (the call into `six`) of the parsl-internals bit of the trace.

So this looks good to merge.

**Comment by a-detiste** [comment]
Thanks for the review.  The whole point of 'six' was t get Python3-like behaviour on Python2 already, so it s quite expected but still pleasant to see nice codebades works as expected without this crutch.

😄😁

**Pull request merged**
