### PR TITLE
Reduce flake8 max-line-length

### PR DESCRIPTION
**Pull request by nawarajshah**
# Description

Reduce flake8 max-line-length
Issue https://github.com/Parsl/parsl/issues/3105

# Changed Behaviour

Which existing user workflows or functionality will behave differently after this PR?

# Fixes

Fixes # (issue)

## Type of change

Choose which options apply, and delete the ones which do not apply.

- Bug fix
- New feature
- Update to human readable text: Documentation/error messages/comments
- Code maintenance/cleanup

### CODE REVIEW

**Comment by benclifford** [comment]
It looks like this PR actually deletes all of parsl - is that what you intended?

**Review by benclifford — CHANGES_REQUESTED** [review]
probably this is not what you intended

**Comment by nawarajshah** [comment]
> probably this is not what you intended

For get the put the issue

**Comment by benclifford** [comment]
The Outreachy application period is over, so I'm closing your PR - thanks for your participation in Parsl+Outreachy so far!

**Pull request closed without merging**
