### PR TITLE
Tests #128

### LINKED ISSUE #128: Tweak test organization
This is related to #121. When the Jenkins server is setup, we will regularly run all of the tests before PRs are merged. That will require that any contributor can exactly reproduce whatever tests are going to be run, to be sure that their feature branch passes and address any issues beforehand. Therefore, we should tweak the tests to remove hardcoded usernames.

### LINKED ISSUE #157: Fix broken tests
@yadudoc this looks related to #151?

```
======================================================================
ERROR: Test checkpointing with task_periodic behavior
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/virtualenv/python3.5.5/lib/python3.5/site-packages/nose/case.py", line 198, in runTest
    self.test(*self.arg)
  File "/home/travis/build/Parsl/parsl/parsl/tests/test_checkpointing/test_periodic.py", line 69, in test_periodic
    assert int(deltas[1] - deltas[0]) == 5, "Delta between checkpoints exceeded period "
IndexError: list index out of range
```

### LINKED ISSUE #159: Make tests self-contained
We currently have some tests that are not self-contained-- for example, this works:
```
(for test in parsl/tests/test_checkpointing/test*; do nosetests -vx $test || exit; done ) ; echo $?
```
but this fails:
```
nosetests -xv  parsl/tests/test_checkpointing
```
The tests should be self-contained such that this isn't required, and each test can be run individually to determine if it passes.

### LINKED ISSUE #192: Refactor tests and sites
As suggested by @kylechard 

We have different tests for each executor (`test_ipp`, `test_threads`, `test_swift.py`) and different sites (`test_sites`). We should refactor the tests such that there is one core set of tests and we cycle through the various executors and sites to run each one.

### PR DESCRIPTION
**Pull request by annawoodard**
This PR implements a change in testing philosophy: instead of writing multiple tests to run the same code on different configurations, the configurations and code are now factorized. By default pytest will run all of the tests on all of the configurations in `parsl/parsl/tests/configs`.  To run a specific config, use `pytest tests --config config.py`. Configurations for remote sites which require user-specific options are collected in `user_opts.py`. Any sites that haven't been configured will be skipped. In this way, as you configure sites, you can gradually add to the sites that you test. I removed a lot of redundancy, but running all of the tests on all of the configurations currently takes a long time, and sometimes hangs. For that reason, for now I recommend running `pytest tests --basic`, which only runs local_ipp and local_threads. I will open separate issues about speeding up tests, pruning remaining redundancies, and fixing broken tests and those that do not assert anything (I have skipped these for now; a summary of skipped tests will be printed when you run the tests). 

Fixes #128, fixes #192, fixes #157, fixes #159.

Example output:
```
> ~/ci/parsl/parsl/tests> pytests --basic
==================================================== test session starts =====================================================
platform darwin -- Python 3.6.2, pytest-3.5.1, py-1.5.3, pluggy-0.6.0
rootdir: /Users/awoodard/ci/parsl/parsl/tests, inifile: pytest.ini
plugins: xdist-1.22.2, timeout-1.2.1, ordering-0.5, lazy-fixture-0.4.0, forked-0.2
collected 290 items / 8 skipped

test_aalst_patterns.py ssssssssssssssssssssssssss                                                                      [  8%]
test_cleanup.py .                                                                                                      [  9%]
test_docker_multisite.py s                                                                                             [  9%]
test_factory.py ..                                                                                                     [ 10%]
test_module.py ss                                                                                                      [ 11%]
test_swift.py sss                                                                                                      [ 12%]
test_thread_parallelism.py ss                                                                                          [ 12%]
test_bash_apps/test_apptimeout.py .                                                                                    [ 13%]
test_bash_apps/test_basic.py ..                                                                                        [ 13%]
test_bash_apps/test_error_codes.py ..s.s.                                                                              [ 15%]
test_bash_apps/test_file_bug_1.py .                                                                                    [ 16%]
test_bash_apps/test_multiline.py .                                                                                     [ 16%]
test_bash_apps/test_pipeline.py ..                                                                                     [ 17%]
test_bash_apps/test_stdout.py ..                                                                                       [ 17%]
test_checkpointing/test_periodic.py s                                                                                  [ 18%]
test_checkpointing/test_python_checkpoint_1.py s                                                                       [ 18%]
test_checkpointing/test_python_checkpoint_2.py ss                                                                      [ 19%]
test_checkpointing/test_python_checkpoint_3.py s                                                                       [ 19%]
test_checkpointing/test_regression_233.py sss                                                                          [ 20%]
test_checkpointing/test_regression_239.py ss                                                                           [ 21%]
test_checkpointing/test_task_exit.py s                                                                                 [ 21%]
test_data/test_file.py ss                                                                                              [ 22%]
test_data/test_file_apps.py ..                                                                                         [ 23%]
test_data/test_file_ipp.py ...                                                                                         [ 24%]
test_docs/test_from_slides.py .                                                                                        [ 24%]
test_docs/test_tutorial_1.py ss                                                                                        [ 25%]
test_docs/test_workflow1.py .                                                                                          [ 25%]
test_docs/test_workflow2.py s                                                                                          [ 25%]
test_docs/test_workflow3.py .                                                                                          [ 26%]
test_docs/test_workflow4.py .                                                                                          [ 26%]
test_error_handling/test_rand_fail.py sssss                                                                            [ 28%]
test_error_handling/test_retries.py sss                                                                                [ 29%]
test_flowcontrol/test_bash.py .                                                                                        [ 29%]
test_flowcontrol/test_python.py s                                                                                      [ 30%]
test_flowcontrol/test_python_diamond.py s                                                                              [ 30%]
test_python_apps/test_at_scale.py sss                                                                                  [ 31%]
test_python_apps/test_basic.py ...s.                                                                                   [ 33%]
test_python_apps/test_configs.py s                                                                                     [ 33%]
test_python_apps/test_fibonacci_iterative.py .                                                                         [ 33%]
test_python_apps/test_fibonacci_recursive.py .                                                                         [ 34%]
test_python_apps/test_futures.py ....                                                                                  [ 35%]
test_python_apps/test_import_fail.py ..                                                                                [ 36%]
test_python_apps/test_mapred.py ..                                                                                     [ 36%]
test_python_apps/test_memoize_1.py ..                                                                                  [ 37%]
test_python_apps/test_memoize_2.py s                                                                                   [ 37%]
test_python_apps/test_memoize_3.py s                                                                                   [ 38%]
test_python_apps/test_memoize_4.py .                                                                                   [ 38%]
test_python_apps/test_memoize_5.py .                                                                                   [ 38%]
test_python_apps/test_outputs.py .                                                                                     [ 39%]
test_python_apps/test_overview.py ..                                                                                   [ 40%]
test_python_apps/test_pipeline.py ..                                                                                   [ 40%]
test_python_apps/test_rand_fail.py ...                                                                                 [ 41%]
test_python_apps/test_simple.py ..                                                                                     [ 42%]
test_python_apps/test_type5.py ..                                                                                      [ 43%]
test_python_apps/test_worker_fail.py .                                                                                 [ 43%]
test_regression/test_221.py .                                                                                          [ 43%]
test_regression/test_226.py ...                                                                                        [ 44%]
test_regression/test_69a.py ss                                                                                         [ 45%]
test_regression/test_69b.py ..s..                                                                                      [ 47%]
test_regression/test_97.py s                                                                                           [ 47%]
test_regression/test_98.py s                                                                                           [ 47%]
test_sites/test_local_ipp_multisite.py ss                                                                              [ 48%]
test_sites/test_local_threads_ipp.py ss                                                                                [ 49%]
test_sites/test_scaling_local.py s                                                                                     [ 49%]
test_aalst_patterns.py ssssssssssssssssssssssssss                                                                      [ 58%]
test_cleanup.py .                                                                                                      [ 58%]
test_docker_multisite.py s                                                                                             [ 59%]
test_factory.py ..                                                                                                     [ 60%]
test_module.py ss                                                                                                      [ 60%]
test_swift.py sss                                                                                                      [ 61%]
test_thread_parallelism.py ss                                                                                          [ 62%]
test_bash_apps/test_apptimeout.py .                                                                                    [ 62%]
test_bash_apps/test_basic.py ..                                                                                        [ 63%]
test_bash_apps/test_error_codes.py ssssss                                                                              [ 65%]
test_bash_apps/test_file_bug_1.py .                                                                                    [ 65%]
test_bash_apps/test_multiline.py .                                                                                     [ 66%]
test_bash_apps/test_pipeline.py ..                                                                                     [ 66%]
test_bash_apps/test_stdout.py ss                                                                                       [ 67%]
test_checkpointing/test_periodic.py s                                                                                  [ 67%]
test_checkpointing/test_python_checkpoint_1.py s                                                                       [ 68%]
test_checkpointing/test_python_checkpoint_2.py ss                                                                      [ 68%]
test_checkpointing/test_python_checkpoint_3.py s                                                                       [ 69%]
test_checkpointing/test_regression_233.py sss                                                                          [ 70%]
test_checkpointing/test_regression_239.py ss                                                                           [ 71%]
test_checkpointing/test_task_exit.py s                                                                                 [ 71%]
test_data/test_file.py ss                                                                                              [ 72%]
test_data/test_file_apps.py ..                                                                                         [ 72%]
test_data/test_file_ipp.py ...                                                                                         [ 73%]
test_docs/test_from_slides.py .                                                                                        [ 74%]
test_docs/test_tutorial_1.py ss                                                                                        [ 74%]
test_docs/test_workflow1.py .                                                                                          [ 75%]
test_docs/test_workflow2.py s                                                                                          [ 75%]
test_docs/test_workflow3.py .                                                                                          [ 75%]
test_docs/test_workflow4.py .                                                                                          [ 76%]
test_error_handling/test_rand_fail.py sssss                                                                            [ 77%]
test_error_handling/test_retries.py sss                                                                                [ 78%]
test_flowcontrol/test_bash.py .                                                                                        [ 79%]
test_flowcontrol/test_python.py s                                                                                      [ 79%]
test_flowcontrol/test_python_diamond.py s                                                                              [ 80%]
test_python_apps/test_at_scale.py sss                                                                                  [ 81%]
test_python_apps/test_basic.py ...s.                                                                                   [ 82%]
test_python_apps/test_configs.py s                                                                                     [ 83%]
test_python_apps/test_fibonacci_iterative.py .                                                                         [ 83%]
test_python_apps/test_fibonacci_recursive.py .                                                                         [ 83%]
test_python_apps/test_futures.py ....                                                                                  [ 85%]
test_python_apps/test_import_fail.py ..                                                                                [ 85%]
test_python_apps/test_mapred.py ..                                                                                     [ 86%]
test_python_apps/test_memoize_1.py ..                                                                                  [ 87%]
test_python_apps/test_memoize_2.py s                                                                                   [ 87%]
test_python_apps/test_memoize_3.py s                                                                                   [ 87%]
test_python_apps/test_memoize_4.py .                                                                                   [ 88%]
test_python_apps/test_memoize_5.py .                                                                                   [ 88%]
test_python_apps/test_outputs.py s                                                                                     [ 88%]
test_python_apps/test_overview.py ..                                                                                   [ 89%]
test_python_apps/test_pipeline.py ..                                                                                   [ 90%]
test_python_apps/test_rand_fail.py ...                                                                                 [ 91%]
test_python_apps/test_simple.py ..                                                                                     [ 92%]
test_python_apps/test_type5.py ..                                                                                      [ 92%]
test_python_apps/test_worker_fail.py .                                                                                 [ 93%]
test_regression/test_221.py .                                                                                          [ 93%]
test_regression/test_226.py ...                                                                                        [ 94%]
test_regression/test_69a.py ss                                                                                         [ 95%]
test_regression/test_69b.py ..s..                                                                                      [ 96%]
test_regression/test_97.py s                                                                                           [ 97%]
test_regression/test_98.py s                                                                                           [ 97%]
test_sites/test_local_ipp_multisite.py ss                                                                              [ 98%]
test_sites/test_local_threads_ipp.py ss                                                                                [ 98%]
test_sites/test_scaling_local.py s                                                                                     [ 99%]
test_bash_apps/test_basic.py ..                                                                                        [100%]
================================================== short test summary info ===================================================
SKIP [2] /Users/awoodard/ci/parsl/parsl/tests/configs/midway_ipp.py:9: midway user_opts not configured {}
SKIP [2] /Users/awoodard/ci/parsl/parsl/tests/configs/local_threads_globus.py:9: globus user_opts not configured
SKIP [1] /Users/awoodard/ci/parsl/parsl/tests/configs/cooley_local_single_node.py:9: cooley user_opts not configured
SKIP [1] /Users/awoodard/ci/parsl/parsl/tests/configs/cori_ipp_multinode.py:20: cori user_opts not configured
SKIP [1] /Users/awoodard/ci/parsl/parsl/tests/configs/cori_ipp_multinode_MPI.py:20: cori user_opts not configured
SKIP [1] /Users/awoodard/ci/parsl/parsl/tests/configs/midway_ipp_multicore.py:9: midway user_opts not configured
SKIP [52] test_aalst_patterns.py: not asserting anything
SKIP [2] test_docker_multisite.py:67: broken
SKIP [42] /Users/awoodard/ci/parsl/parsl/tests/conftest.py:163: skipping non-local config
SKIP [1] /Users/awoodard/ci/parsl/parsl/tests/conftest.py:149: config '/Users/awoodard/ci/parsl/parsl/tests/configs/local_threads.py' not in whitelist
SKIP [2] test_thread_parallelism.py:25: fails intermittently in pytest
SKIP [2] test_thread_parallelism.py:46: fails intermittently in pytest
SKIP [2] test_bash_apps/test_error_codes.py:100: broken
SKIP [2] test_bash_apps/test_error_codes.py:133: broken
SKIP [2] test_checkpointing/test_periodic.py:30: fails intermittently
SKIP [2] test_checkpointing/test_regression_239.py:49: fails intermittently in pytest
SKIP [2] test_checkpointing/test_regression_239.py:69: fails intermittently in pytest
SKIP [2] test_checkpointing/test_task_exit.py:22: fails intermittently in pytest
SKIP [2] test_docs/test_tutorial_1.py:23: hangs in pytest
SKIP [2] test_docs/test_tutorial_1.py:36: hangs in pytest
SKIP [2] test_docs/test_workflow2.py:23: fails with pytest+xdist
SKIP [2] test_error_handling/test_rand_fail.py:48: broken
SKIP [2] test_error_handling/test_rand_fail.py:72: broken
SKIP [2] test_error_handling/test_rand_fail.py:98: broken
SKIP [2] test_error_handling/test_rand_fail.py:153: broken
SKIP [2] test_error_handling/test_retries.py:51: broken
SKIP [2] test_error_handling/test_retries.py:69: broken
SKIP [2] test_error_handling/test_retries.py:92: broken
SKIP [2] test_flowcontrol/test_python_diamond.py:20: slow and does not assert anything
SKIP [2] test_python_apps/test_at_scale.py:21: not asserting anything
SKIP [2] test_python_apps/test_at_scale.py:36: not asserting anything
SKIP [2] test_python_apps/test_at_scale.py:51: not asserting anything
SKIP [2] test_python_apps/test_basic.py:80: broken
SKIP [2] test_python_apps/test_configs.py:19: fails intermittently
SKIP [2] test_regression/test_69a.py:28: fails in pytest
SKIP [2] test_regression/test_69a.py:48: fails in pytest
SKIP [2] test_regression/test_69b.py:56: fails intermittently; too sensitive to machine load
SKIP [2] test_regression/test_97.py:26: this test needs to be fixed or removed; it appears we do not expect it to complete
SKIP [2] test_sites/test_local_ipp_multisite.py:37: broken in pytest
SKIP [2] test_sites/test_scaling_local.py:10: broken
SKIP [1] /Users/awoodard/ci/parsl/parsl/tests/conftest.py:149: config '/Users/awoodard/ci/parsl/parsl/tests/configs/local_ipp.py' not in whitelist
SKIP [7] /Users/awoodard/ci/parsl/parsl/tests/conftest.py:151: broken in IPP

========================================= 125 passed, 173 skipped in 525.30 seconds ==========================================

### CODE REVIEW

**Comment by benclifford** [comment]
On my dev machine, commit f58becf2cfa7d24f0ed3ba77d8c82ae6c1d90ddb:

pytest --basic

...
=================================== FAILURES ===================================
 test_at_task_exit[/home/benc/parsl/src/parsl/parsl/tests/configs/local_ipp.py] 

n = 4

    def test_at_task_exit(n=4):
        """Test checkpointing at task_exit behavior
        """
    
        d = {}
    
        print("Launching : ", n)
        for i in range(0, n):
            d[i] = slow_double(i)
        print("Done launching")
    
        for i in range(0, n):
            d[i].result()
        print("Done sleeping")
    
        dfk.cleanup()
        print("Rundir : ", dfk.rundir)
        with open("{}/parsl.log".format(dfk.rundir), 'r') as f:
            expected_msg = "Done checkpointing {} tasks".format(n)
            lines = [line for line in f.readlines() if expected_msg in line]
>           assert len(lines) == 1, "Expected {} checkpoint events, got {}".format(1, len(lines))
E           AssertionError: Expected 1 checkpoint events, got 2
E           assert 2 == 1
E            +  where 2 = len(['2018-05-11 19:26:19 parsl.dataflow.dflow:662 [INFO]  Done checkpointing 4 tasks\n', '2018-05-11 19:27:42 parsl.dataflow.dflow:662 [INFO]  Done checkpointing 4 tasks\n'])

test_checkpointing/test_dfk_exit.py:50: AssertionError

...

================================================= 1 failed, 66 passed, 131 skipped in 106.83 seconds ==================================================

**Comment by annawoodard** [comment]
@benclifford It looks like that file is from somewhere else? I do not see `test_dfk_exit.py` on master or on `tests-#128`. On a related note: I think pytest's formatting of errors is nice; I like how it prints the whole log line here.

In general these tests that check the logs do not play nicely with automated testing frameworks. We should switch to checking the checkpoint explicitly (like in `test_task_exit.py`) instead of the log.

**Comment by benclifford** [comment]
@annawoodard yeah, corrupt checkout here.

**Comment by annawoodard** [comment]
@benclifford thanks for testing!

**Pull request merged**
