### PR TITLE
Fix blocking Work Queue executor send/retrieve loop

### LINKED ISSUE #2801: investigate task-end-to-task-end delays in Work Queue
**Describe the bug**
Performance is poor in the work queue executor when running sequential tasks: the time from one task ending to the next task starting is around 1 second. I'm not sure if this is inside the parsl wq executor code, or inside core wq.

**To Reproduce**
submit two tasks, one which depends on the other. observe a 1 second delay between task 1 completing on the worker and task 2 starting on the worker.

**Expected behavior**
This could be much faster.

**Environment**
my laptop

cc @khk-globus

### PR DESCRIPTION
**Pull request by colinthomas-z80**
# Description
The Work Queue executor was attempting to wait for tasks when there were none in the queue, causing the timeout period to be observed in the task throughput. 

Now the executor re-checks whether the queue is empty before attempting to wait on another task retrieval.

# Fixes

#2801 

Choose which options apply, and delete the ones which do not apply.

- Bug fix

### CODE REVIEW

**Comment by colinthomas-z80** [comment]
@benclifford Is there anything further you'd like from this? If all is good I can make an equivalent taskvine PR or add on here

**Comment by benclifford** [comment]
@colinthomas-z80 hi - I'm not waiting on anything from you but I don't think any more PR reviews will happen in 2023.

**Comment by benclifford** [comment]
This drops the runtime of the pytest suite on my laptop from 7 minutes to 10 seconds.

I also used `git diff -r origin/master --color-moved --color-moved-ws=allow-indentation-change` to check that all the indentation changes didn't change anything else in that main block.

**Review by benclifford — APPROVED** [review]

**Comment by benclifford** [comment]
I think this change means that the Work Queue Executor submit/wait process will now use 100% CPU because there is nothing stopping it from hard looping checking both submit and result queues continuously. That hard loop comes from the loop trying to do two things and maybe would be fixed by splitting this loop into two loops that can then each perform their own long wait without interfering with the other half.

**Pull request merged**
