### PR TITLE
[WIP] continuing work on rearranging app futures

### PR DESCRIPTION
**Pull request by benclifford**

### CODE REVIEW

**Comment by benclifford** [comment]
I've pulled out the hopefully-easy parts of this PR to be #835, #837, #838, which leaves less in this PR to think about.

**Comment by benclifford** [comment]
More of this PR is pulled out into #1200

**Comment by benclifford** [comment]
@hategan - this is a branch that I've been slowly merging piece by piece into master over the last year. If you're looking at callback handling/tidying this might be something to look at.

#1200 was the most recent piece I moved around The final bit of rearrangement that I wanted to do was replace the call `self.tasks[task_id]['app_fu'].parent_callback(future)` introduced in #1200 to call the AppFuture callback, by pasting in the actual code from `AppFuture.parent_callback` so that AppFuture would have no parent_callback at all any more.

The point of this would be to move as much code as makes sense on task state management into the DFK code. The most immediate thing that I am uncomfortable with is retry handling: there's a "distributed if-else" that lives part in `AppFuture.parent_callback` and part in the `DFK.handle_exec_update`. Having moved parent_callback into the DFK code, I would hope that it would be easier to turn this into a regular `if-then-else` block.

**Comment by yadudoc** [comment]
@benclifford Is this PR still valid ? Has this been merged to master in parts already ?

**Comment by benclifford** [comment]
@yadudoc still one more part to go

**Comment by benclifford** [comment]
#1431 should be the last PR needed to merge this.

**Comment by benclifford** [comment]
All the pieces I wanted to get merged have now been merged in one form or another.

**Pull request closed without merging**
