### PR TITLE
Update CONTRIBUTING.rst

### PR DESCRIPTION
**Pull request by danielskatz**
# Description

trying to make CONTRIBUTING friendlier

## Type of change

Choose which options apply, and delete the ones which do not apply.

- Documentation update

### CODE REVIEW

**Comment by danielskatz** [comment]
It would also be good to add

* Expected time frame for response
* That we express gratitude to contributors in the language we use
* Who decides whether to accept my contribution? How are decisions about the project made?
* What is the contributor’s responsibility after submitting a PR?
* Is the contribution within the roadmap/vision of the project?

But I'm not sure exactly how to do this

**Review by yadudoc — APPROVED** [review]
Adding the slack link in there makes sense. :+1:

**Comment by yadudoc** [comment]
@danielskatz Would be good to cover the items you raised in the parsl meeting.

**Comment by benclifford** [comment]
> Expected time frame for response
> Who decides whether to accept my contribution? How are decisions about the project made?
> What is the contributor’s responsibility after submitting a PR?
> Is the contribution within the roadmap/vision of the project?
> But I'm not sure exactly how to do this

I think attempting to write anything about the above in a contributing document when there isn't consensus on the answers would be a frustrating experience that will result in text that is confusing and wrong. Though they seem valid points that could benefit from consensus building.

**Pull request merged**
