### PR TITLE
Fix lsf

### PR DESCRIPTION
**Pull request by hannayjd**
# Description

When using the LSF provider we ran into many exceptions and crashes when utilizing the scale in and scale out feature.
Found some small bugs and updated the LSF provider code by using the SLURM provider code as a guide.
These changes fixed our LSF issues and successfully ran problems that automatically scaled in and out.
Would like to give back to the community and hopefully help anyone else using the LSF scheduler.

Fixes # (issue)
Could not find an existing issue for LSF provider.

## Type of change

Choose which options apply, and delete the ones which do not apply.

- Bug fix (non-breaking change that fixes an issue)

### CODE REVIEW

**Comment by benclifford** [comment]
cool, thanks. Yadu is listed as the tech sponsor for LSF in #2554 so hopefully he can give this a test/review.

**Review by yadudoc — COMMENTED** [review]
Changes here look good. Thanks for contributing these bits :) 
I'm waiting on getting my Summit.OLCF account reactivated to test these changes, it's the only machine I have access to that runs LSF. I'm hoping to have this sorted out this week.

**Comment by bnebgen-LANL** [comment]
Suggest addition at line 176 of lsf.py:
`if len(line_list) < 3:
    continue`
Some LSF systems print batch_hosts by default, causing _status to error. 

Otherwise, changes are working for me.

**Comment by swfc** [comment]
> Suggest addition at line 176 of lsf.py: ` if len(line_list) < 3:
> 
> ```
> continue
> ```
> 
> ` Some LSF systems print batch_hosts by default, causing _status to error.
> 
> Otherwise, changes are working for me. These fixes are much appreciated.

Thanks for checking. I've updated the PR to handle different LSF configs by specifically requesting the JOBID and STAT columns as well as other checking that the job_id is parsed correctly from the bjobs command.

**Comment by hannayjd** [comment]
> Suggest addition at line 176 of lsf.py: ` if len(line_list) < 3:
> 
> ```
> continue
> ```
> 
> ` Some LSF systems print batch_hosts by default, causing _status to error.
> 
> Otherwise, changes are working for me. These fixes are much appreciated.

Thanks for checking. I've updated the PR to handle different LSF configs by specifically requesting the JOBID and STAT columns as well as other checking that the job_id is parsed correctly from the bjobs command.

**Comment by bnebgen-LANL** [comment]
Checked this version. Working with no errors.

**Comment by benclifford** [comment]
@hannayjd can you merge the latest parsl master to this? (Or make it so I can...). Then can merge this PR.

**Comment by hannayjd** [comment]
> @hannayjd can you merge the latest parsl master to this? (Or make it so I can...). Then can merge this PR.

@benclifford should be good now. Thanks.

**Pull request merged**
