### PR TITLE
unify launch plus callback unlocking

### PR DESCRIPTION
**Pull request by benclifford**

### CODE REVIEW

**Comment by annawoodard** [comment]
I think this should fix #461

**Comment by annawoodard** [comment]
[graph-size.pdf](https://github.com/Parsl/parsl/files/2503698/graph-size.pdf)

Here is a plot showing performance improvement due to this PR.

**Comment by benclifford** [comment]
needs #580 merging first (or more specifically, #580 is part of this that i'd like to appear on master separately)

**Comment by benclifford** [comment]
On digging into callback behaviour a bit more and looking at retry behaviour (which we aren't testing!), it looks like callbacks get lost.

I'll dig into this a little more.

**Comment by annawoodard** [comment]
superseded by #600

**Pull request closed without merging**
