### PR TITLE
Adding github actions for CI

### LINKED ISSUE #2077: Move CI away from travis
**Is your feature request related to a problem? Please describe.**

Travis CI free open source tier is now only available to projects which have no paid development.

We've repeatedly run out of credits in CI, and this is now interfering with our ability to merge PRs.

CI has been incredibly valuable and there should be no question about switching it off.

Yadu mentioned privately to me that he was going to try github actions.

### PR DESCRIPTION
**Pull request by yadudoc**
# Description

This PR adds a github actions workflow template that replicates our current CI setup in Travis.

Fixes #2077 

## Type of change

Choose which options apply, and delete the ones which do not apply.

- New feature (non-breaking change that adds functionality)
- Code maintentance/cleanup

### CODE REVIEW

**Comment by benclifford** [comment]
at the moment this is hitting a problem importing work_queue. The existing CI workqueue installer is pretty dodgy - it installs a binary that links against libpython3.5m, no matter which version of python is being used, leading to things like this:

> ImportError: libpython3.5m.so.1.0: cannot open shared object file: No such file or directory

That happens to work in travis, but not on (eg) my laptop.

The work queue installer should be made nicer.

**Review by yadudoc — COMMENTED** [review]
Changes look good, and the tests are running and passing on github so that's great.
In one of the runs this test hung: `parsl/tests/test_flowcontrol/test_one_block.py . `.
The test hanging for 6hours (360mins) seems excessive, maybe we should limit it to 45mins?
https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idtimeout-minutes

**Comment by benclifford** [comment]
I added a 40 minute timeout. In the next test run, one of the `--config local` steps hung and was successfully terminated (after 40 minutes since the start of the run, about 15 minutes of being hung).

Hopefully once this PR is merged, I can resume investigating CI hangs again - trying to debug that in Travis is what caused the messing up of our travis account which is what caused this move to Github Actions.

**Comment by yadudoc** [comment]
@benclifford, now that we have a sensible timeout, I think we should get this merged. However since I started this PR, I cannot approve it, maybe @danielskatz or @kylechard can?

**Review by danielskatz — APPROVED** [review]
reviewed but not really checked, which probably is a "bad thing"

**Pull request merged**
