### PR TITLE
Reduce flake8 max-line-length

### PR DESCRIPTION
**Pull request by MundiaNderi**
# Description

Checking Pep-8 compliance on .flake8 file. Tested the file with pycodestyle .flake8 to see the errors there before reverting to make flake8.

# Changed Behaviour

No change in behaviour. 

# Fixes
Fixes # (3105)

## Type of change

Choose which options apply, and delete the ones which do not apply.
- Code maintenance/cleanup

### CODE REVIEW

**Comment by benclifford** [comment]
Hi. When I look at your changes, https://github.com/Parsl/parsl/pull/3126/files - it looks like you didn't commit anything to change the line length or to fix any resulting problems. Maybe you misunderstood that step in the instructions or made a pull request from the wrong branch.

**Comment by MundiaNderi** [comment]
Maybe I misunderstood.  I created a new fork from https://github.com/Parsl/parsl and with that I followed the instructions outlined. Kindly what do you suggest I do? Delete the forked repository and start afresh

**Comment by MundiaNderi** [comment]
Thank you @benclifford . Since when I cloned the repository the max-line-length = 157 was already 157, and 156 was not raising any flake8 errors I changed the line length to 155.

**Comment by benclifford** [comment]
yes that looks more like what I was expecting. there are still some messy bits in your PR though - some files that didn't need changing. if you look in the "Files Changed" tab of this pull request you can probably see those changes, in addition to the ones you added just now.

Other people and PRs have already brought the line length down to 154, so you can either work on making it even smaller, or you can move onto looking through the other issues we have tagged with `outreachy` to find something you'd like to learn more about and work on: https://github.com/Parsl/parsl/issues?q=is%3Aissue+is%3Aopen+label%3Aoutreachy

**Comment by MundiaNderi** [comment]
Hey @benclifford I've brought it down to 150 and I would also like to pick another issue from the list. if when you decrease the maximum number of characters to a certain number and make flake8 throws errors, how do you decipher which files need changing? For 150 I made changes to all the files with errors. Should I close this PR and reopen it or should I create an entirely new PR?

**Comment by MundiaNderi** [comment]
@benclifford reduced the max-length to 150

**Pull request closed without merging**
