### PR TITLE
Add support for GPU kubernetes grids

### PR DESCRIPTION
**Pull request by MatthewBM**
# Description

Added option to specify number of GPUs to assign to pods in kubernetes provider

## Type of change

Choose which options apply, and delete the ones which do not apply.

- New feature (non-breaking change that adds functionality)

### CODE REVIEW

**Comment by benclifford** [comment]
My gut says that it would be to allow a user to specify arbitrary resource requests and limits in the configuration, rather than hard-coding specific choices for which request and limits are allow.

See how the slurm provider has a scheduler_options parameter to allow arbitrary slurm options to be specified.

That could be an `extra_request` dict and an `extra_limits` dict that are merged with the appropriate dict at the point that this PR adds in the n_gpus entries.

This would allow the same option to support other resource limits - I think `hugepages` and `ephemeral-storage` are available but unsupported by parsl at the moment, for example.

**Comment by MatthewBM** [comment]
> My gut says that it would be better to allow a user to specify arbitrary resource requests and limits in the configuration, rather than hard-coding specific choices for which request and limits are allow.
> 
> See how the slurm provider has a scheduler_options parameter to allow arbitrary slurm options to be specified.
> 
> That could be an `extra_request` dict and an `extra_limits` dict that are merged with the appropriate dict at the point that this PR adds in the n_gpus entries.
> 
> This would allow the same option to support other resource limits - I think `hugepages` and `ephemeral-storage` are available but unsupported by parsl at the moment, for example.

**Comment by benclifford** [comment]
@MatthewBM I think this functionality would be useful to have merged -- just suggesting a more generic possibility

**Comment by MatthewBM** [comment]
Yes I agree I'll do some more work on it, I'm realizing that some kubernetes grids configurations may not have nvidia.com/gpu as a resource label at all so that code could cause exceptions there. I'll update this in the next few days.

**Pull request closed without merging**
