### PR TITLE
clarify that max workers is per node

### PR DESCRIPTION
**Pull request by benclifford**
## Type of change

- Documentation update

### CODE REVIEW

**Comment by ZhuozhaoLi** [comment]
Is it better to even make it a breaking change? i.e., change it to `max_workers_per_node`

**Comment by benclifford** [comment]
maybe. this PR is not intended to achieve that.

**Review by yadudoc — APPROVED** [review]
@benclifford I agree with the documentation change. Unfortunately, most users don't read the docs, and it helps to have the config option be more descriptive. Would you be open to a separate PR adding a new `max_workers_per_node` option in addition and deprecating max_workers in the release after?

**Comment by benclifford** [comment]
i'm fine with someone else doing that

**Pull request merged**
