### PR TITLE
Make retry tests wait for all launched tasks before finishing

### PR DESCRIPTION
**Pull request by benclifford**
Without this, the tasks continue to run while subsequent local
tests happen. This is at the least confusing in logs - I haven't
checked if it introduces any actual testing problems.

## Type of change

- Bug fix (non-breaking change that fixes an issue)

### CODE REVIEW

**Review by yadudoc — COMMENTED** [review]
This test will not wait for all tasks if the assertion fails. It's not clear what exactly the second wait accomplishes.

**Comment by benclifford** [comment]
The remaining tasks continue executing after the test function finishes, and their resulting DFK log traffic is interleaved with subsequent test log traffic in the next DFK in the same python process. This PR adds a barrier to make sure they are all finished before moving onto the next test - `--config local` tests should not leave tasks running after they claim to be finished by returning.

**Comment by benclifford** [comment]
most of this was merged as part of #2205 but yadu's comment on ordering of results still needs fixing here

**Comment by yadudoc** [comment]
@benclifford I hope you don't mind me converting this to draft. At this point, this PR is a placeholder for changes that aren't ready.

**Review by yadudoc — APPROVED** [review]
Alright, this looks correct now. Let's merge.

**Pull request merged**
