### PR TITLE
Also offer BibTeX citation snippet

### PR DESCRIPTION
**Pull request by katrinleinweber**
Hello :-)

would this be of interest as well? It's the same snippet that Zenodo exports.

Cheers!

### CODE REVIEW

**Comment by danielskatz** [comment]
This seems like a good addition to me.

Alternatively, we could include [BibTeX](https://zenodo.org/record/853492/export/hx)

or a copy of what's in Export on the bottom right of https://zenodo.org/record/853492#.WtiO1y-ZOJQ

I'm not sure which would be best.

**Comment by yadudoc** [comment]
This is a super useful addition @katrinleinweber !

**Comment by danielskatz** [comment]
@yadudoc @annawoodard  Did you read my comment above?

**Comment by annawoodard** [comment]
> Alternatively, we could include "BibTeX"

I don't follow, this PR is bibtex.

> or a copy of what's in Export on the bottom right of https://zenodo.org/record/853492#.WtiO1y-ZOJQ
I think this would be nice but will take more time; we should open it as a separate issue.

**Comment by danielskatz** [comment]
we could copy the "BibTex" link from the zenodo page, and let it resolve back to the Zenodo page itself

Or we could copy all the output options from the zenodo page.

**Comment by danielskatz** [comment]
basically, my question is we should duplicate the bibtex info on our page or point (link) to what zenodo generates directly

**Comment by annawoodard** [comment]
I would say that far and away bibtex will be the most common citation method, so I prefer putting the text directly as is done in this PR, because it saves people time. We can add a link separately, i.e., "for more options, visit here"

**Comment by katrinleinweber** [comment]
You're welcome, and thanks for merging :-)

**Pull request merged**
