### PR TITLE
Log choice of executor for a task as soon as it is chosen

### PR DESCRIPTION
**Pull request by benclifford**
Previously this was not logged until after the task had been
successfully submitted.

## Type of change

- New feature (non-breaking change that adds functionality)

### CODE REVIEW

**Review by yadudoc — COMMENTED** [review]
This is soon followed by a log message of the form "Task <TID> launched on <executor>", so I'm not sure what this adds?

**Comment by benclifford** [comment]
it's not followed by that message when the task isn't successfully launched - you end up with a stack trace for some executor without which executor configuration tried to launch it

**Comment by yadudoc** [comment]
Okay, that makes sense. Perhaps this should be a debug log line.

**Comment by benclifford** [comment]
@yadudoc i've change the log level for the new message

**Review by yadudoc — APPROVED** [review]

**Pull request merged**
