### PR TITLE
Remove unused import (from `ruff . --fix`)

### PR DESCRIPTION
**Pull request by Andrew-S-Rosen**
# Description

I applied [ruff](https://github.com/astral-sh/ruff) autofixes (i.e. `ruff . --fix`) to the source code, which found... precisely one unused import. 😅 

## Type of change

- Code maintentance/cleanup

### CODE REVIEW

**Comment by benclifford** [comment]
i feel like this removed a lot more than it should have

**Comment by Andrew-S-Rosen** [comment]
@benclifford: There should only be one commit. You probably saw an older commit where I also ran `ruff` on the test suite, which wreaked havoc on things.

**Comment by benclifford** [comment]
the existing tooling usually catches unused imports - it's interesting that it didn't catch this one

**Comment by benclifford** [comment]
I realised why the one file this PR ended up modifying wasn't picked up by flake8: it's because this file isn't source code, but instead output code generated by `poncho_package_serverize` and committed into the Parsl tree (see PR #2605).

It makes less sense to edit machine generated object code, even though it happens to be in Python syntax - this isn't a file for humans to be editing, and changes to that file should be via changing how `poncho_package_serverize` creates that file, or by editing the source file `parsl_coprocess_stub.py`.

In a more pure build system, this file wouldn't exist in version control and would be built from the stub file at compile/build time - but that isn't what's happening, so this file ends up as a violation of "don't commit object code into version control" instead.

**Comment by Andrew-S-Rosen** [comment]
Ah, well now that clears things up!

**Pull request merged**
