### PR TITLE
ENH kill condor jobs at shutdown

### PR DESCRIPTION
**Pull request by beckermr**
# Description

Please include a summary of the change and (optionally) which issue is fixed. Please also include
relevant motivation and context.

Fixes # (issue)

## Type of change

Choose which options apply, and delete the ones which do not apply.

- Bug fix (non-breaking change that fixes an issue)
- New feature (non-breaking change that adds functionality)
- Breaking change (fix or feature that would cause existing functionality to not work as expected)
- Documentation update
- Code maintentance/cleanup

### CODE REVIEW

**Comment by benclifford** [comment]
this should already be handled by the scaling in code automatically scaling in all of the blocks at dfk cleanup (which fires atexit) - without this PR, do you see attempts at that happening in your parsl.log?

**Comment by beckermr** [comment]
We see the attempts but the scaling code is missing jobs and leaving them running.

**Comment by beckermr** [comment]
I think managers on jobs that don't connect back are left running.

**Comment by benclifford** [comment]
if the scaling in code isn't scaling in some blocks, that sounds like it would be a problem when running other providers too - can you attach a parsl.log to an issue with this happening?

**Comment by benclifford** [comment]
hm - that isn't how it's meant to work - or rather, managers do get told to shut down, but then blocks should also be killed by the provider mechanism, separately, independently of what any processes inside those blocks are doing.

the shutdown code in parsl is fairly error-prone, though, so I wouldn't be surprised if something is going awry there.

**Comment by esheldon** [comment]
Note there were 100 jobs/workers running but it only tried to kill 74, and there were 74 orphaned jobs.

[parsl.log](https://github.com/Parsl/parsl/files/7669697/parsl.log)

**Comment by esheldon** [comment]
sorry, 100 - 74 = 26 orphaned jobs

**Comment by benclifford** [comment]
ok send a log and lets trace whats happening to those.

**Comment by benclifford** [comment]
(a whole parsl.log to start with)

**Comment by esheldon** [comment]
I attached it above

**Comment by benclifford** [comment]
oops, yep, sorry

**Comment by benclifford** [comment]
ok, this is suspiciously similar numbers:

```
Executor HighThroughputExecutor has 8 active tasks, 73/27 running/pending blocks, and 74 connected workers
```

The scaling code thinks there are 27 pending blocks... maybe those are the ones that it isn't trying to kill.

I'm not sure:

i) why those are pending rather than running -- that information should be nothing to do with what the manager process is doing.

Is condor setting failed jobs back to pending in the condor job queue? (if so, that's probably confusing to parsl)

ii) why those blocks aren't being passed to condor_rm - it makes sense that every block should be killed, no matter what state they are in.

I'll have a look through the code to see if anything is obvious there.

**Comment by benclifford** [comment]
ok, I'm wrong -- the scale in code in the high throughput executor only scales in blocks that have had a successful manager registration, from a quick look at 'def scale_in' in parsl/executors/high_throughput/executor.py

If so, that's going to be a problem with any provider, not just condor, and it should be straightforward to reproduce.

cc @yadudoc @ZhuozhaoLi who are closer to this piece of the code than me

**Comment by beckermr** [comment]
Thank you so much @benclifford for looking into this! 

I wonder if this PR should be merged anyways to ensure cleanup if there is a bug or issue somewhere else though? We could add some signal handling as well. The goal is to never orphan a job and having more than once method by which we attempt to kill jobs is useful I think.

**Pull request closed without merging**
