### PR TITLE
Add worker plot monitoring #1278

### PR DESCRIPTION
**Pull request by ZhuozhaoLi**
This PR adds a worker efficiency plot to the resource page of workflow.

The worker efficiency is computed by `total_running_tasks/total_workers`.

`total_running_tasks` is to count the total number of running tasks every one second (by checking if the `task_time_running` and `task_time_returned` include that timestamp).

`total_workers` is computed by adding up the `worker_count` in the `node` table (current assumption is that there is no scaling. If we want to have scaling, we need to add more info to the `node` table)

### CODE REVIEW

**Comment by ZhuozhaoLi** [comment]
Fixes #1278

**Comment by yadudoc** [comment]
I'm seeing this error now : 
`The worker efficiency plot cannot be generated because of exception can't multiply sequence by non-int of type 'numpy.float64'.`

**Comment by yadudoc** [comment]
Issue #1286 will be addressed separately where we'll handle the case where we have events besides worker registration logged for monitoring.

**Comment by ZhuozhaoLi** [comment]
> I'm seeing this error now :
> `The worker efficiency plot cannot be generated because of exception can't multiply sequence by non-int of type 'numpy.float64'.`

Now it returns an exception saying that the plot cannot be produced due to missing data.

**Pull request merged**
