### PR TITLE
Treat python_app input/output default arguments like other magic keywords, and like bash_app

### PR DESCRIPTION
**Pull request by arhag23**
# Description

In a previous PR (#3485), some fields where the default values of `outputs` and `inputs` for AppBase were removed. These fields were not being used in any way. However, like the other parsl reserved parameters, the defaults should have been stored in the `AppBase.kwargs` dict which is used to ensure that the default values of these special reserved parameters are in `invocation_kwargs` which is sent to the dataflow kernel and used to resolve the corresponding special behaviors. The correct behavior was only observed in `BashApp` since it does additional checking to store all default args (even the non-reserved ones) to `invocation_kwargs`. Now it should be consistent for both types of apps.

# Changed Behaviour

`PythonApp` will now correctly resolve default arguments for the `inputs` and `outputs` special parameters.

## Type of change

- Bug fix
- Code maintenance/cleanup

### CODE REVIEW

**Comment by benclifford** [comment]
`parsl/tests/test_staging/test_zip_out.py` is failing in CI - perhaps also for you locally?

**Comment by arhag23** [comment]
I'm not able to run the entire test suite locally, but I tried running the individual test that fails and it seems to run fine locally.

**Comment by astro-friedel** [comment]
From the logs it appears that `test_bash_multiple_set` from `test_mpi_mode_enabled.py` is the test that is failing for python 3.8 with a serialization error. I do see that the CI test were run mutiple times, each one failed at a different spot with the same serialization error. I have been unable to run the full test suite for Parslas I cannot find a compatible `cctools` for my OS (ubuntu 22.04), so I am unable to reproduce the error locally.

**Comment by benclifford** [comment]
For future, the error that @astro-friedel is referring to that has appeared a few times looks like this below paste.

The non-obvious bit of this (to me) is that the code is trying to serialize a `Queue` object. That shouldn't ever be happening, and its not clear to me where in the serialization graph that Queue object is coming from - the stack trace doesn't give a huge amount of information about the internal structure of whats being serialized.

I'll try to dig into debugging this more seriously in the next few days.

```
2024-06-14T20:17:34.2816704Z DEBUG    parsl.dataflow.dflow:dflow.py:687 Got an exception launching task
2024-06-14T20:17:34.2816818Z Traceback (most recent call last):
2024-06-14T20:17:34.2817437Z   File "/home/runner/work/parsl/parsl/parsl/executors/high_throughput/executor.py", line 668, in submit
2024-06-14T20:17:34.2817642Z     fn_buf = pack_res_spec_apply_message(func, args, kwargs,
2024-06-14T20:17:34.2818111Z   File "/home/runner/work/parsl/parsl/parsl/serialize/facade.py", line 87, in pack_res_spec_apply_message
2024-06-14T20:17:34.2818498Z     return pack_apply_message(func, args, (kwargs, resource_specification), buffer_threshold=buffer_threshold)
2024-06-14T20:17:34.2818908Z   File "/home/runner/work/parsl/parsl/parsl/serialize/facade.py", line 58, in pack_apply_message
2024-06-14T20:17:34.2819100Z     b_func = serialize(func, buffer_threshold=buffer_threshold)
2024-06-14T20:17:34.2819460Z   File "/home/runner/work/parsl/parsl/parsl/serialize/facade.py", line 125, in serialize
2024-06-14T20:17:34.2819554Z     raise result
2024-06-14T20:17:34.2819903Z   File "/home/runner/work/parsl/parsl/parsl/serialize/facade.py", line 117, in serialize
2024-06-14T20:17:34.2820182Z     result = method.identifier + b'\n' + method.serialize(obj)
2024-06-14T20:17:34.2820558Z   File "/home/runner/work/parsl/parsl/parsl/serialize/concretes.py", line 61, in serialize
2024-06-14T20:17:34.2820747Z     return dill.dumps(data)
2024-06-14T20:17:34.2821259Z   File "/home/runner/work/parsl/parsl/.venv/lib/python3.8/site-packages/dill/_dill.py", line 280, in dumps
2024-06-14T20:17:34.2821495Z     dump(obj, file, protocol, byref, fmode, recurse, **kwds)#, strictio)
2024-06-14T20:17:34.2821982Z   File "/home/runner/work/parsl/parsl/.venv/lib/python3.8/site-packages/dill/_dill.py", line 252, in dump
2024-06-14T20:17:34.2822121Z     Pickler(file, protocol, **_kwds).dump(obj)
2024-06-14T20:17:34.2823029Z   File "/home/runner/work/parsl/parsl/.venv/lib/python3.8/site-packages/dill/_dill.py", line 420, in dump
2024-06-14T20:17:34.2823259Z     StockPickler.dump(self, obj)
2024-06-14T20:17:34.2823906Z   File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/pickle.py", line 487, in dump
2024-06-14T20:17:34.2824088Z     self.save(obj)
2024-06-14T20:17:34.2825264Z   File "/home/runner/work/parsl/parsl/.venv/lib/python3.8/site-packages/dill/_dill.py", line 414, in save
2024-06-14T20:17:34.2825594Z     StockPickler.save(self, obj, save_persistent_id)
2024-06-14T20:17:34.2826086Z   File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/pickle.py", line 560, in save
2024-06-14T20:17:34.2826286Z     f(self, obj)  # Call unbound method with explicit self
2024-06-14T20:17:34.2826900Z   File "/home/runner/work/parsl/parsl/.venv/lib/python3.8/site-packages/dill/_dill.py", line 1985, in save_function
2024-06-14T20:17:34.2827068Z     _save_with_postproc(pickler, (_create_function, (
2024-06-14T20:17:34.2827653Z   File "/home/runner/work/parsl/parsl/.venv/lib/python3.8/site-packages/dill/_dill.py", line 1098, in _save_with_postproc
2024-06-14T20:17:34.2827801Z     pickler.save_reduce(*reduction, obj=obj)
2024-06-14T20:17:34.2828178Z   File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/pickle.py", line 717, in save_reduce
2024-06-14T20:17:34.2828266Z     save(state)
2024-06-14T20:17:34.2828766Z   File "/home/runner/work/parsl/parsl/.venv/lib/python3.8/site-packages/dill/_dill.py", line 414, in save
2024-06-14T20:17:34.2828935Z     StockPickler.save(self, obj, save_persistent_id)
2024-06-14T20:17:34.2829273Z   File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/pickle.py", line 560, in save
2024-06-14T20:17:34.2829527Z     f(self, obj)  # Call unbound method with explicit self
2024-06-14T20:17:34.2830123Z   File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/pickle.py", line 886, in save_tuple
2024-06-14T20:17:34.2830290Z     save(element)
2024-06-14T20:17:34.2831196Z   File "/home/runner/work/parsl/parsl/.venv/lib/python3.8/site-packages/dill/_dill.py", line 414, in save
2024-06-14T20:17:34.2831390Z     StockPickler.save(self, obj, save_persistent_id)
2024-06-14T20:17:34.2831785Z   File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/pickle.py", line 560, in save
2024-06-14T20:17:34.2832111Z     f(self, obj)  # Call unbound method with explicit self
2024-06-14T20:17:34.2833421Z   File "/home/runner/work/parsl/parsl/.venv/lib/python3.8/site-packages/dill/_dill.py", line 1217, in save_module_dict
2024-06-14T20:17:34.2833711Z     StockPickler.save_dict(pickler, obj)
2024-06-14T20:17:34.2834374Z   File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/pickle.py", line 971, in save_dict
2024-06-14T20:17:34.2834603Z     self._batch_setitems(obj.items())
2024-06-14T20:17:34.2835313Z   File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/pickle.py", line 997, in _batch_setitems
2024-06-14T20:17:34.2835429Z     save(v)
2024-06-14T20:17:34.2836004Z   File "/home/runner/work/parsl/parsl/.venv/lib/python3.8/site-packages/dill/_dill.py", line 414, in save
2024-06-14T20:17:34.2836294Z     StockPickler.save(self, obj, save_persistent_id)
2024-06-14T20:17:34.2836765Z   File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/pickle.py", line 603, in save
2024-06-14T20:17:34.2836988Z     self.save_reduce(obj=obj, *rv)
2024-06-14T20:17:34.2837468Z   File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/pickle.py", line 692, in save_reduce
2024-06-14T20:17:34.2837727Z     save(args)
2024-06-14T20:17:34.2838270Z   File "/home/runner/work/parsl/parsl/.venv/lib/python3.8/site-packages/dill/_dill.py", line 414, in save
2024-06-14T20:17:34.2838442Z     StockPickler.save(self, obj, save_persistent_id)
2024-06-14T20:17:34.2838786Z   File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/pickle.py", line 560, in save
2024-06-14T20:17:34.2838968Z     f(self, obj)  # Call unbound method with explicit self
2024-06-14T20:17:34.2839350Z   File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/pickle.py", line 886, in save_tuple
2024-06-14T20:17:34.2839440Z     save(element)
2024-06-14T20:17:34.2839946Z   File "/home/runner/work/parsl/parsl/.venv/lib/python3.8/site-packages/dill/_dill.py", line 414, in save
2024-06-14T20:17:34.2840109Z     StockPickler.save(self, obj, save_persistent_id)
2024-06-14T20:17:34.2840546Z   File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/pickle.py", line 560, in save
2024-06-14T20:17:34.2840742Z     f(self, obj)  # Call unbound method with explicit self
2024-06-14T20:17:34.2841327Z   File "/home/runner/work/parsl/parsl/.venv/lib/python3.8/site-packages/dill/_dill.py", line 1985, in save_function
2024-06-14T20:17:34.2841494Z     _save_with_postproc(pickler, (_create_function, (
2024-06-14T20:17:34.2842078Z   File "/home/runner/work/parsl/parsl/.venv/lib/python3.8/site-packages/dill/_dill.py", line 1098, in _save_with_postproc
2024-06-14T20:17:34.2842220Z     pickler.save_reduce(*reduction, obj=obj)
2024-06-14T20:17:34.2842594Z   File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/pickle.py", line 717, in save_reduce
2024-06-14T20:17:34.2842682Z     save(state)
2024-06-14T20:17:34.2843491Z   File "/home/runner/work/parsl/parsl/.venv/lib/python3.8/site-packages/dill/_dill.py", line 414, in save
2024-06-14T20:17:34.2843707Z     StockPickler.save(self, obj, save_persistent_id)
2024-06-14T20:17:34.2844069Z   File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/pickle.py", line 560, in save
2024-06-14T20:17:34.2844423Z     f(self, obj)  # Call unbound method with explicit self
2024-06-14T20:17:34.2844814Z   File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/pickle.py", line 886, in save_tuple
2024-06-14T20:17:34.2844905Z     save(element)
2024-06-14T20:17:34.2845431Z   File "/home/runner/work/parsl/parsl/.venv/lib/python3.8/site-packages/dill/_dill.py", line 414, in save
2024-06-14T20:17:34.2845598Z     StockPickler.save(self, obj, save_persistent_id)
2024-06-14T20:17:34.2845928Z   File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/pickle.py", line 560, in save
2024-06-14T20:17:34.2846104Z     f(self, obj)  # Call unbound method with explicit self
2024-06-14T20:17:34.2846670Z   File "/home/runner/work/parsl/parsl/.venv/lib/python3.8/site-packages/dill/_dill.py", line 1217, in save_module_dict
2024-06-14T20:17:34.2846800Z     StockPickler.save_dict(pickler, obj)
2024-06-14T20:17:34.2847536Z   File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/pickle.py", line 971, in save_dict
2024-06-14T20:17:34.2847678Z     self._batch_setitems(obj.items())
2024-06-14T20:17:34.2848101Z   File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/pickle.py", line 1002, in _batch_setitems
2024-06-14T20:17:34.2848185Z     save(v)
2024-06-14T20:17:34.2848704Z   File "/home/runner/work/parsl/parsl/.venv/lib/python3.8/site-packages/dill/_dill.py", line 414, in save
2024-06-14T20:17:34.2848863Z     StockPickler.save(self, obj, save_persistent_id)
2024-06-14T20:17:34.2849193Z   File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/pickle.py", line 560, in save
2024-06-14T20:17:34.2849362Z     f(self, obj)  # Call unbound method with explicit self
2024-06-14T20:17:34.2849967Z   File "/home/runner/work/parsl/parsl/.venv/lib/python3.8/site-packages/dill/_dill.py", line 1985, in save_function
2024-06-14T20:17:34.2850196Z     _save_with_postproc(pickler, (_create_function, (
2024-06-14T20:17:34.2850790Z   File "/home/runner/work/parsl/parsl/.venv/lib/python3.8/site-packages/dill/_dill.py", line 1098, in _save_with_postproc
2024-06-14T20:17:34.2851033Z     pickler.save_reduce(*reduction, obj=obj)
2024-06-14T20:17:34.2851404Z   File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/pickle.py", line 692, in save_reduce
2024-06-14T20:17:34.2851499Z     save(args)
2024-06-14T20:17:34.2851999Z   File "/home/runner/work/parsl/parsl/.venv/lib/python3.8/site-packages/dill/_dill.py", line 414, in save
2024-06-14T20:17:34.2852166Z     StockPickler.save(self, obj, save_persistent_id)
2024-06-14T20:17:34.2852516Z   File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/pickle.py", line 560, in save
2024-06-14T20:17:34.2852691Z     f(self, obj)  # Call unbound method with explicit self
2024-06-14T20:17:34.2853075Z   File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/pickle.py", line 901, in save_tuple
2024-06-14T20:17:34.2853165Z     save(element)
2024-06-14T20:17:34.2853666Z   File "/home/runner/work/parsl/parsl/.venv/lib/python3.8/site-packages/dill/_dill.py", line 414, in save
2024-06-14T20:17:34.2853832Z     StockPickler.save(self, obj, save_persistent_id)
2024-06-14T20:17:34.2854168Z   File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/pickle.py", line 560, in save
2024-06-14T20:17:34.2854346Z     f(self, obj)  # Call unbound method with explicit self
2024-06-14T20:17:34.2854715Z   File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/pickle.py", line 886, in save_tuple
2024-06-14T20:17:34.2854807Z     save(element)
2024-06-14T20:17:34.2855289Z   File "/home/runner/work/parsl/parsl/.venv/lib/python3.8/site-packages/dill/_dill.py", line 414, in save
2024-06-14T20:17:34.2855446Z     StockPickler.save(self, obj, save_persistent_id)
2024-06-14T20:17:34.2855774Z   File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/pickle.py", line 560, in save
2024-06-14T20:17:34.2855943Z     f(self, obj)  # Call unbound method with explicit self
2024-06-14T20:17:34.2856314Z   File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/pickle.py", line 931, in save_list
2024-06-14T20:17:34.2856421Z     self._batch_appends(obj)
2024-06-14T20:17:34.2856823Z   File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/pickle.py", line 955, in _batch_appends
2024-06-14T20:17:34.2856909Z     save(x)
2024-06-14T20:17:34.2857397Z   File "/home/runner/work/parsl/parsl/.venv/lib/python3.8/site-packages/dill/_dill.py", line 414, in save
2024-06-14T20:17:34.2857561Z     StockPickler.save(self, obj, save_persistent_id)
2024-06-14T20:17:34.2858048Z   File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/pickle.py", line 603, in save
2024-06-14T20:17:34.2858193Z     self.save_reduce(obj=obj, *rv)
2024-06-14T20:17:34.2858590Z   File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/pickle.py", line 717, in save_reduce
2024-06-14T20:17:34.2858687Z     save(state)
2024-06-14T20:17:34.2859187Z   File "/home/runner/work/parsl/parsl/.venv/lib/python3.8/site-packages/dill/_dill.py", line 414, in save
2024-06-14T20:17:34.2859343Z     StockPickler.save(self, obj, save_persistent_id)
2024-06-14T20:17:34.2859766Z   File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/pickle.py", line 560, in save
2024-06-14T20:17:34.2859950Z     f(self, obj)  # Call unbound method with explicit self
2024-06-14T20:17:34.2860533Z   File "/home/runner/work/parsl/parsl/.venv/lib/python3.8/site-packages/dill/_dill.py", line 1217, in save_module_dict
2024-06-14T20:17:34.2860658Z     StockPickler.save_dict(pickler, obj)
2024-06-14T20:17:34.2861033Z   File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/pickle.py", line 971, in save_dict
2024-06-14T20:17:34.2861146Z     self._batch_setitems(obj.items())
2024-06-14T20:17:34.2861537Z   File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/pickle.py", line 997, in _batch_setitems
2024-06-14T20:17:34.2861624Z     save(v)
2024-06-14T20:17:34.2862109Z   File "/home/runner/work/parsl/parsl/.venv/lib/python3.8/site-packages/dill/_dill.py", line 414, in save
2024-06-14T20:17:34.2862271Z     StockPickler.save(self, obj, save_persistent_id)
2024-06-14T20:17:34.2862597Z   File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/pickle.py", line 560, in save
2024-06-14T20:17:34.2862838Z     f(self, obj)  # Call unbound method with explicit self
2024-06-14T20:17:34.2863207Z   File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/pickle.py", line 931, in save_list
2024-06-14T20:17:34.2863311Z     self._batch_appends(obj)
2024-06-14T20:17:34.2863705Z   File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/pickle.py", line 958, in _batch_appends
2024-06-14T20:17:34.2863793Z     save(tmp[0])
2024-06-14T20:17:34.2864290Z   File "/home/runner/work/parsl/parsl/.venv/lib/python3.8/site-packages/dill/_dill.py", line 414, in save
2024-06-14T20:17:34.2864446Z     StockPickler.save(self, obj, save_persistent_id)
2024-06-14T20:17:34.2864764Z   File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/pickle.py", line 603, in save
2024-06-14T20:17:34.2864879Z     self.save_reduce(obj=obj, *rv)
2024-06-14T20:17:34.2865333Z   File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/pickle.py", line 692, in save_reduce
2024-06-14T20:17:34.2865485Z     save(args)
2024-06-14T20:17:34.2866099Z   File "/home/runner/work/parsl/parsl/.venv/lib/python3.8/site-packages/dill/_dill.py", line 414, in save
2024-06-14T20:17:34.2866262Z     StockPickler.save(self, obj, save_persistent_id)
2024-06-14T20:17:34.2866581Z   File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/pickle.py", line 560, in save
2024-06-14T20:17:34.2866749Z     f(self, obj)  # Call unbound method with explicit self
2024-06-14T20:17:34.2867117Z   File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/pickle.py", line 886, in save_tuple
2024-06-14T20:17:34.2867206Z     save(element)
2024-06-14T20:17:34.2867694Z   File "/home/runner/work/parsl/parsl/.venv/lib/python3.8/site-packages/dill/_dill.py", line 414, in save
2024-06-14T20:17:34.2867848Z     StockPickler.save(self, obj, save_persistent_id)
2024-06-14T20:17:34.2868179Z   File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/pickle.py", line 560, in save
2024-06-14T20:17:34.2868352Z     f(self, obj)  # Call unbound method with explicit self
2024-06-14T20:17:34.2869136Z   File "/home/runner/work/parsl/parsl/.venv/lib/python3.8/site-packages/dill/_dill.py", line 1473, in save_instancemethod0
2024-06-14T20:17:34.2869396Z     pickler.save_reduce(MethodType, (obj.__func__, obj.__self__), obj=obj)
2024-06-14T20:17:34.2869920Z   File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/pickle.py", line 692, in save_reduce
2024-06-14T20:17:34.2870042Z     save(args)
2024-06-14T20:17:34.2870562Z   File "/home/runner/work/parsl/parsl/.venv/lib/python3.8/site-packages/dill/_dill.py", line 414, in save
2024-06-14T20:17:34.2870716Z     StockPickler.save(self, obj, save_persistent_id)
2024-06-14T20:17:34.2871042Z   File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/pickle.py", line 560, in save
2024-06-14T20:17:34.2871210Z     f(self, obj)  # Call unbound method with explicit self
2024-06-14T20:17:34.2871694Z   File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/pickle.py", line 886, in save_tuple
2024-06-14T20:17:34.2871792Z     save(element)
2024-06-14T20:17:34.2872284Z   File "/home/runner/work/parsl/parsl/.venv/lib/python3.8/site-packages/dill/_dill.py", line 414, in save
2024-06-14T20:17:34.2872437Z     StockPickler.save(self, obj, save_persistent_id)
2024-06-14T20:17:34.2872756Z   File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/pickle.py", line 603, in save
2024-06-14T20:17:34.2872868Z     self.save_reduce(obj=obj, *rv)
2024-06-14T20:17:34.2873236Z   File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/pickle.py", line 717, in save_reduce
2024-06-14T20:17:34.2873327Z     save(state)
2024-06-14T20:17:34.2873802Z   File "/home/runner/work/parsl/parsl/.venv/lib/python3.8/site-packages/dill/_dill.py", line 414, in save
2024-06-14T20:17:34.2873963Z     StockPickler.save(self, obj, save_persistent_id)
2024-06-14T20:17:34.2874285Z   File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/pickle.py", line 560, in save
2024-06-14T20:17:34.2874458Z     f(self, obj)  # Call unbound method with explicit self
2024-06-14T20:17:34.2875102Z   File "/home/runner/work/parsl/parsl/.venv/lib/python3.8/site-packages/dill/_dill.py", line 1217, in save_module_dict
2024-06-14T20:17:34.2875277Z     StockPickler.save_dict(pickler, obj)
2024-06-14T20:17:34.2875791Z   File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/pickle.py", line 971, in save_dict
2024-06-14T20:17:34.2875910Z     self._batch_setitems(obj.items())
2024-06-14T20:17:34.2876312Z   File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/pickle.py", line 997, in _batch_setitems
2024-06-14T20:17:34.2876394Z     save(v)
2024-06-14T20:17:34.2876887Z   File "/home/runner/work/parsl/parsl/.venv/lib/python3.8/site-packages/dill/_dill.py", line 414, in save
2024-06-14T20:17:34.2877046Z     StockPickler.save(self, obj, save_persistent_id)
2024-06-14T20:17:34.2877364Z   File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/pickle.py", line 603, in save
2024-06-14T20:17:34.2877489Z     self.save_reduce(obj=obj, *rv)
2024-06-14T20:17:34.2877849Z   File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/pickle.py", line 717, in save_reduce
2024-06-14T20:17:34.2877943Z     save(state)
2024-06-14T20:17:34.2878435Z   File "/home/runner/work/parsl/parsl/.venv/lib/python3.8/site-packages/dill/_dill.py", line 414, in save
2024-06-14T20:17:34.2878595Z     StockPickler.save(self, obj, save_persistent_id)
2024-06-14T20:17:34.2878924Z   File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/pickle.py", line 560, in save
2024-06-14T20:17:34.2879179Z     f(self, obj)  # Call unbound method with explicit self
2024-06-14T20:17:34.2880200Z   File "/home/runner/work/parsl/parsl/.venv/lib/python3.8/site-packages/dill/_dill.py", line 1217, in save_module_dict
2024-06-14T20:17:34.2880352Z     StockPickler.save_dict(pickler, obj)
2024-06-14T20:17:34.2880741Z   File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/pickle.py", line 971, in save_dict
2024-06-14T20:17:34.2880857Z     self._batch_setitems(obj.items())
2024-06-14T20:17:34.2881261Z   File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/pickle.py", line 997, in _batch_setitems
2024-06-14T20:17:34.2881356Z     save(v)
2024-06-14T20:17:34.2881876Z   File "/home/runner/work/parsl/parsl/.venv/lib/python3.8/site-packages/dill/_dill.py", line 414, in save
2024-06-14T20:17:34.2882045Z     StockPickler.save(self, obj, save_persistent_id)
2024-06-14T20:17:34.2882377Z   File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/pickle.py", line 560, in save
2024-06-14T20:17:34.2882554Z     f(self, obj)  # Call unbound method with explicit self
2024-06-14T20:17:34.2882921Z   File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/pickle.py", line 886, in save_tuple
2024-06-14T20:17:34.2883010Z     save(element)
2024-06-14T20:17:34.2883509Z   File "/home/runner/work/parsl/parsl/.venv/lib/python3.8/site-packages/dill/_dill.py", line 414, in save
2024-06-14T20:17:34.2883670Z     StockPickler.save(self, obj, save_persistent_id)
2024-06-14T20:17:34.2884122Z   File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/pickle.py", line 603, in save
2024-06-14T20:17:34.2884443Z     self.save_reduce(obj=obj, *rv)
2024-06-14T20:17:34.2884837Z   File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/pickle.py", line 717, in save_reduce
2024-06-14T20:17:34.2884968Z     save(state)
2024-06-14T20:17:34.2885704Z   File "/home/runner/work/parsl/parsl/.venv/lib/python3.8/site-packages/dill/_dill.py", line 414, in save
2024-06-14T20:17:34.2885886Z     StockPickler.save(self, obj, save_persistent_id)
2024-06-14T20:17:34.2886230Z   File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/pickle.py", line 560, in save
2024-06-14T20:17:34.2886463Z     f(self, obj)  # Call unbound method with explicit self
2024-06-14T20:17:34.2887124Z   File "/home/runner/work/parsl/parsl/.venv/lib/python3.8/site-packages/dill/_dill.py", line 1217, in save_module_dict
2024-06-14T20:17:34.2887254Z     StockPickler.save_dict(pickler, obj)
2024-06-14T20:17:34.2887634Z   File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/pickle.py", line 971, in save_dict
2024-06-14T20:17:34.2887895Z     self._batch_setitems(obj.items())
2024-06-14T20:17:34.2888304Z   File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/pickle.py", line 997, in _batch_setitems
2024-06-14T20:17:34.2888389Z     save(v)
2024-06-14T20:17:34.2888895Z   File "/home/runner/work/parsl/parsl/.venv/lib/python3.8/site-packages/dill/_dill.py", line 414, in save
2024-06-14T20:17:34.2889060Z     StockPickler.save(self, obj, save_persistent_id)
2024-06-14T20:17:34.2889388Z   File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/pickle.py", line 603, in save
2024-06-14T20:17:34.2889501Z     self.save_reduce(obj=obj, *rv)
2024-06-14T20:17:34.2889873Z   File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/pickle.py", line 717, in save_reduce
2024-06-14T20:17:34.2889965Z     save(state)
2024-06-14T20:17:34.2890450Z   File "/home/runner/work/parsl/parsl/.venv/lib/python3.8/site-packages/dill/_dill.py", line 414, in save
2024-06-14T20:17:34.2890717Z     StockPickler.save(self, obj, save_persistent_id)
2024-06-14T20:17:34.2891324Z   File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/pickle.py", line 560, in save
2024-06-14T20:17:34.2891645Z     f(self, obj)  # Call unbound method with explicit self
2024-06-14T20:17:34.2892729Z   File "/home/runner/work/parsl/parsl/.venv/lib/python3.8/site-packages/dill/_dill.py", line 1217, in save_module_dict
2024-06-14T20:17:34.2892972Z     StockPickler.save_dict(pickler, obj)
2024-06-14T20:17:34.2893647Z   File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/pickle.py", line 971, in save_dict
2024-06-14T20:17:34.2893875Z     self._batch_setitems(obj.items())
2024-06-14T20:17:34.2894325Z   File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/pickle.py", line 997, in _batch_setitems
2024-06-14T20:17:34.2894418Z     save(v)
2024-06-14T20:17:34.2894976Z   File "/home/runner/work/parsl/parsl/.venv/lib/python3.8/site-packages/dill/_dill.py", line 414, in save
2024-06-14T20:17:34.2895154Z     StockPickler.save(self, obj, save_persistent_id)
2024-06-14T20:17:34.2895493Z   File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/pickle.py", line 578, in save
2024-06-14T20:17:34.2895605Z     rv = reduce(self.proto)
2024-06-14T20:17:34.2895828Z TypeError: cannot pickle '_queue.SimpleQueue' object
2024-06-14T20:17:34.2895837Z 
2024-06-14T20:17:34.2896068Z During handling of the above exception, another exception occurred:
2024-06-14T20:17:34.2896074Z 
2024-06-14T20:17:34.2896192Z Traceback (most recent call last):
2024-06-14T20:17:34.2896622Z   File "/home/runner/work/parsl/parsl/parsl/dataflow/dflow.py", line 677, in _launch_if_ready_async
2024-06-14T20:17:34.2896753Z     exec_fu = self.launch_task(task_record)
2024-06-14T20:17:34.2897113Z   File "/home/runner/work/parsl/parsl/parsl/dataflow/dflow.py", line 765, in launch_task
2024-06-14T20:17:34.2897507Z     exec_fu = executor.submit(function, task_record['resource_specification'], *args, **kwargs)
2024-06-14T20:17:34.2898295Z   File "/home/runner/work/parsl/parsl/parsl/executors/high_throughput/executor.py", line 672, in submit
2024-06-14T20:17:34.2898475Z     raise SerializationError(func.__name__)
2024-06-14T20:17:34.2899481Z parsl.serialize.errors.SerializationError: Failed to serialize objects for an invocation of function echo_launch_cmd. Refer https://parsl.readthedocs.io/en/latest/faq.html#addressing-serializationerror
```

**Comment by benclifford** [comment]
one thing that is suspicious from that stack is that ...

```
2024-06-14T20:17:34.2846670Z   File "/home/runner/work/parsl/parsl/.venv/lib/python3.8/site-packages/dill/_dill.py", line 1217, in save_module_dict
```

... it looks like the code is trying to serialize a module (probably the containing module for a defined function) which is almost always not what should be happening in Parsl, and that can sometimes lead to bringing in way more spurious stuff into the object graph...

So that's probably the first place I'll start poking.

**Comment by benclifford** [comment]
i'm able to recreate this locally by running these two test cases in a specific sequence:

```
$ pytest parsl/tests/test_bash_apps/test_inputs_default.py parsl/tests/test_mpi_apps/test_mpi_mode_enabled.py  --config local
```

something happening in this newly introduced test_inputs_default test is interacting badly with what's happening in that MPI test, to do with module and function definitions...

**Comment by benclifford** [comment]
another pairing that fails for me locally: `pytest parsl/tests/test_bash_apps/test_inputs_default.py parsl/tests/test_staging/test_zip_out.py --config local`

**Comment by benclifford** [comment]
I made this change to a copy of your branch and it seems to make things work. I mostly understand what's going on there (and it's something that shouldn't have been happening in parsl, that just happens to have never apparently broken before...)

https://github.com/Parsl/parsl/pull/3490/commits/49a335fd50bba1c45a9711431d510653b7baaedd

I'll write up a proper pull request for just this change with more details.

**Comment by benclifford** [comment]
@arhag23 @astro-friedel I'm hoping that PR #3492 fixes this test failure.

**Comment by benclifford** [comment]
@arhag23 #3492 is merged and this PR passes tests now - so I think its OK to merge, if you're happy with it too

**Comment by arhag23** [comment]
Yes, I'm happy it in this state.

**Review by benclifford — APPROVED** [review]

**Comment by benclifford** [comment]
@arhag23  Can you amend your description "In a previous PR, some fields where the default values of outputs and inputs for AppBase were removed." to link to the PR that you are talking about?

**Comment by arhag23** [comment]
I amended it.

**Pull request merged**
