### PR TITLE
Support using spawn instead of fork for HTEx

### PR DESCRIPTION
**Pull request by WardLT**
# Description

Polaris, in particular, has an interaction between MPI and fork which makes HTEx worker pools fail to function when used with an MPILauncher. This PR adds the ability for HTEx to launch workers by spawning a new process rather than forking.

## Type of change

Choose which options apply, and delete the ones which do not apply.

- New feature (non-breaking change that adds functionality)
- Documentation update

### CODE REVIEW

**Comment by WardLT** [comment]
While I'm thinking about it, adding a "Thread" option for launching workers could help with #2264 . Seems like we'd have all kinds of issues with logging for each thread though 🤔

**Comment by benclifford** [comment]
What's the logging issue?

With `fork`, the parent logger already appears in each worker; the worker code conveniently avoids logging to that logging name, but in general a worker can log into the manager log. (I think - it's caused me trouble before)

If it's to do with globals, maybe there are other global problems to be cautious about?

**Comment by WardLT** [comment]
There could be no logging issue. I haven't reviewed the code yet to figure out if starting a worker alters "basicConfig" and messes with everyone-elses logger

**Comment by benclifford** [comment]
I think some resource monitoring stuff wont' work (for the same reason that it doesn't work in the thread pool executor) - the resource monitoring is done by process. (see parsl.monitoring.monitor_wrapper)

I think it's fine for various things to not work. better if some test for invalid config options raises an exception at initialization time for known bad combos (i.e. write the machine readable version of the warning in the documentation)

**Comment by WardLT** [comment]
Sounds great. I'll add that in while it's on the brain

**Comment by WardLT** [comment]
Just confirmed that this runs on at least 256 nodes with 1024 works on Polaris!

**Pull request merged**
