### PR TITLE
Log executable to stdout

### PR DESCRIPTION
**Pull request by annawoodard**

### CODE REVIEW

**Comment by annawoodard** [comment]
The tests are failing because I've added unexpected output to standard out. For example,
```
@bash_app
    def echo_hello(stdout='echo-hello.stdout'):
        return 'echo "Hello, world!"'
```

will produce the following in `echo-hello.stdout`:
```
--> executable follows <--
echo "Hello, world!"
--> standard output follows <--
Hello, world!
```

I did this to avoid having to evaluate the executable in the main parsl process (in order to print it in `parsl.log`), and because I find this more readable. We can either evaluate the executable in the main parsl process and print to `parsl.log`, and leave the standard out as it was previously, or modify the failing tests. Any thoughts?

**Comment by annawoodard** [comment]
Another option would be to write the executable to its own file, but that seems a bit overkill.

**Comment by ZhuozhaoLi** [comment]
I vote to modify the failing tests.

**Comment by annawoodard** [comment]
Thanks for the input everyone! I've changed to logging to stderr, so we should be good to go.

**Pull request merged**
