### PR TITLE
merge duplicate code blocks in htex and simple strategy

### LINKED ISSUE #1862: [htex auto scale] RuntimeError: dictionary changed size during iteration
**Describe the bug**
A RuntimeError exception is thrown (stack trace below) while running a workflow based on Parsl.

```
2020-09-10 00:15:14 parsl.dataflow.dflow:509 [INFO]  Task 0 launched on executor medium
2020-09-10 00:15:14 workflow:68 [INFO]  Waiting for validation task to complete...
2020-09-10 00:15:17 parsl.providers.torque.torque:128 [DEBUG]  coerced job_id 1838438.wlm01 -> 1838438.wlm01
2020-09-10 00:15:17 parsl.dataflow.strategy:332 [DEBUG]  Executor medium has 0 active tasks, 0/1 running/pending blocks, and 0 connected workers
2020-09-10 00:15:17 parsl.dataflow.flow_control:114 [ERROR]  Flow control callback threw an exception - logging and proceeding anyway
Traceback (most recent call last):
  File "/home/akila/Documents/NUS_CSI/Parsl/parsl.git/parsl/dataflow/flow_control.py", line 112, in make_callback
    self.callback(tasks=self._event_buffer, kind=kind)
  File "/home/akila/Documents/NUS_CSI/Parsl/parsl.git/parsl/dataflow/task_status_poller.py", line 66, in poll
    self._strategy.strategize(self._poll_items, tasks)
  File "/home/akila/Documents/NUS_CSI/Parsl/parsl.git/parsl/dataflow/strategy.py", line 302, in _strategy_htex_auto_scale
    for label, executor in self.dfk.executors.items():
RuntimeError: dictionary changed size during iteration
2020-09-10 00:15:22 parsl.providers.torque.torque:128 [DEBUG]  coerced job_id 1838438.wlm01 -> 1838438.wlm01
```

This is similar to the issue reported in #1606 which occurred intermittently when using `strategy='simple'`
The same fix should be done for `htex_auto_scale` which was introduced in #1563

**To Reproduce**
1. Setup Parsl with master branch commit: 5445f90
2. Enable checkpointing and monitoring
3. Set `strategy='htex_auto_scale'` in Parsl config
4. Execute a simple workflow (multiple bash_apps and python_apps chained together)

**Expected behavior**
No RuntimeError exceptions.

**Environment**
OS: RHEL6.1
Python version: 3.7 (Anaconda 4.8.2)
Parsl version: master branch commit: 5445f90

**Distributed Environment**
PBS Pro in NSCC's ASPIRE1

### PR DESCRIPTION
**Pull request by ZhuozhaoLi**
# Description

The new `htex_auto_scale` strategy introduced in #1563 has a substantial amount of code duplicated with the original `simple` strategy. This PR removes the duplicate bits and fixes the inconsistency on the executor status checking between the two strategies.

Specifically, the old executor status checking to loop over the dfk executors caused a race condition in #1862 . This PR should fix #1862.

Fixes #1862 .

## Type of change

Choose which options apply, and delete the ones which do not apply.

- Bug fix (non-breaking change that fixes an issue)
- Code maintentance/cleanup

### CODE REVIEW

**Comment by ZhuozhaoLi** [comment]
@ravihansa3000 Could you please confirm this fix the issue #1862 when you have time? thanks.

**Comment by ravihansa3000** [comment]
@ZhuozhaoLi Thanks for the fix! I've tested the latest commit (098ddd9) using `strategy='htex_auto_scale'` and it seems to have fixed the problem. I ran the workflow multiple times and didn't see the `RuntimeError` exception in the logs.

**Comment by ZhuozhaoLi** [comment]
> @ZhuozhaoLi Thanks for the fix! I've tested the latest commit ([098ddd9](https://github.com/Parsl/parsl/commit/098ddd923bed538a5af946b319b0d6bd6bd4dd6a)) using `strategy='htex_auto_scale'` and it seems to have fixed the problem. I ran the workflow multiple times and didn't see the `RuntimeError` exception in the logs.

Thanks @ravihansa3000 for confirming that.

**Review by yadudoc — APPROVED** [review]
I think these changes look good.

**Pull request merged**
