### PR TITLE
Allow HTEX to set CPU affinity

### LINKED ISSUE #1344: HTEX forcing thread affinity
I have issues around multi-threaded Parsl apps interfering with each other when placed on the same node. Instead of creating my own logic to prevent apps from attempting to use the same CPU cores, it could be nice for Parsl to enforce affinity itself (e.g., with the [`os` module](https://docs.python.org/3/library/os.html#interface-to-the-scheduler)).

**Is your feature request related to a problem? Please describe.**
It is related to my issues resulting from Tensorflow's CPU/GPU affinity (#751)

**Describe the solution you'd like**
For Parsl to force explicity HTEX workers to use certain CPUs.

**Describe alternatives you've considered**
Having users make affinity logic themselves.

**Additional context**
I'm going to work up a solution in my own parsl app and then submit it for review.

### PR DESCRIPTION
**Pull request by WardLT**
# Description

This PR introduces an option for HTEX workers to set their CPU affinity on launch. Setting CPU affinity can prevent multithreaded tasks from interfering with each other (e.g., Tensorflow tasks). 

Fixes #1344 

## Type of change

Choose which options apply, and delete the ones which do not apply.

- New feature (non-breaking change that adds functionality)
- Documentation update

### CODE REVIEW

**Comment by WardLT** [comment]
Any advice for how to test this? I was thinking of setting the `htex_local_alternate` test configuration to use one of the affinity settings.

**Comment by benclifford** [comment]
@wardlt if it is very likely that every system will support affinity, then it makes sense to add it into htex_local_alternate. That won't test if affinity is actually happening, though.

Or, make a local mode test that actually checks (somehow) that affinity is happening.

**Comment by WardLT** [comment]
I placed the test in the `sites` folder, which is where I put the "worker_info" test I made a while back (for reasons I cannot remember). Is that OK?

**Comment by benclifford** [comment]
> I placed the test in the sites folder, which is where I put the "worker_info" test I made a while back (for reasons I cannot remember). Is that OK?

@wardlt yeah that's fine - the structure of test directories is fairly vague and what really matters is that pytest can find the test.

**Comment by benclifford** [comment]
@WardLT you need to merge parsl master into this (ideally using the github user interface) so that it can be tested in CI before being merged into parsl master. Usually there's a button for me to do that myself, but not for this PR (perhaps because it is coming from a different organisation's repo)

**Comment by WardLT** [comment]
Done

**Pull request merged**
