### PR TITLE
parsl.providers.cluster_provider _write_submit_script should return nothing, rather than constant True

### PR DESCRIPTION
**Pull request by mirembe-mariam**
# Description

parsl.providers.cluster_provider _write_submit_script should return nothing, rather than constant True

# Changed Behaviour

Changed the return handling for the cluster_provider _write_submit_script and edited the docstring to match

# Fixes

Fixes # issue #3234

## Type of change

- Bug fix
- New feature
- Update to human readable text: Documentation/error messages/comments
- Code maintenance/cleanup

### CODE REVIEW

**Comment by benclifford** [comment]
Hi. Your tests were failing - see the red x next to one of the checks on this PR. The error it reports (which you can find by clicking Details) is:

```
flake8 parsl/
parsl/providers/cluster_provider.py:94:21: W291 trailing whitespace
parsl/providers/cluster_provider.py:120:15: W291 trailing whitespace
make: *** [Makefile:40: flake8] Error 1
Error: Process completed with exit code 2.
```

PR #3238 also makes this change and is merged now, so you can fix this PR to make the tests pass, if you would like to see how to fix things, or you can move on to doing something else and close this PR without merging.

**Comment by mirembe-mariam** [comment]
> Hi. Your tests were failing - see the red x next to one of the checks on this PR. The error it reports (which you can find by clicking Details) is:
> 
> ```
> flake8 parsl/
> parsl/providers/cluster_provider.py:94:21: W291 trailing whitespace
> parsl/providers/cluster_provider.py:120:15: W291 trailing whitespace
> make: *** [Makefile:40: flake8] Error 1
> Error: Process completed with exit code 2.
> ```
> 
> PR #3238 also makes this change and is merged now, so you can fix this PR to make the tests pass, if you would like to see how to fix things, or you can move on to doing something else and close this PR without merging.

Alright let me fix it

**Comment by mirembe-mariam** [comment]
Hi, @benclifford  I have been able to resolve the issues with the failing tests.

**Comment by benclifford** [comment]
Hi. @jessielin34 got here with PR #3238 just before you did, so I'm closing this PR.

**Pull request closed without merging**
