### PR TITLE
Reduce flake8 max-line-length

### PR DESCRIPTION
**Pull request by Olotuah**
# Description

This documentation outlines the process of reducing the maximum line length in the project's source code. It provides an overview of the changes made to adhere to a new maximum line length limit, enhancing code readability and maintainability.

# Changed Behaviour

After implementing this change, the source code files will adhere to a stricter maximum line length limit. This adjustment improves code readability and ensures consistency throughout the project. Users and developers working with the codebase will benefit from clearer and more concise code formatting.

# Fixes

Fixes # (3105)

## Type of change

- Code maintenance/cleanup

### CODE REVIEW

**Comment by benclifford** [comment]
Your tests are failing - have a look at the error messages which appear in the "Details" link on the "checks" section of this PR. You should also be seeing those when you run `make flake8` in your development environment.

**Comment by benclifford** [comment]
sorry, you should see these errors when you run `make mypy`, not `make flake8`

**Comment by Olotuah** [comment]
Thank you @benclifford  for bringing this to my attention. I'll review the error messages in the 'Details' link of the 'checks' section on the PR, as well as when I run 'make mypy' in my development environment. I'll work on addressing the issues and ensure that the tests pass successfully.

**Comment by benclifford** [comment]
The Outreachy application period is over, so I'm closing your PR - thanks for your participation in Parsl+Outreachy so far!

**Pull request closed without merging**
