### PR TITLE
Added options to set annotations and a service account in the Kuberne…

### PR DESCRIPTION
**Pull request by shishichen**
…tes worker pod configuration

# Description

Added options for pod annotations and a service account to be used by the pod, which are passed through to the Kubernetes client. These options are needed when using the provider on Google Kubernetes Engine for pods to mount Google Cloud Storage persistent volumes.

# Changed Behaviour

Enables additional options to be configured on the Kubernetes worker pods.

# Fixes

Fixes # n/a - minor change

## Type of change

- New feature

### CODE REVIEW

**Comment by benclifford** [comment]
cool I'll try this out on my kubernetes cluster. @trey-stafford @mfisher87 might be in a better place to review this PR than me though.

**Review by benclifford — APPROVED** [review]
I tested out that pods start up with an alternate service account and with some basic annotations.

**Comment by shishichen** [comment]
Thanks for the review!

**Comment by mfisher87** [comment]
@benclifford thanks for looping us in! Unfortunately, our time commitment is temporarily coming to an end this week and don't have time for an in-depth review amongst the other tie-up tasks. We'll be looking at this work again in October! The Python looks great, but my context is super limited :)

One comment not related to this PR: I see some docstrings that have type hints in them, but there are also real Python type annotations on those methods & classes. Does your autodoc engine read the Python type annotations? In which case the docstring hints could be removed to simplify maintenance.

**Pull request merged**
