### PR TITLE
Use concurrency in the README

### PR DESCRIPTION
**Pull request by WardLT**
# Description

It bothers me that there is no parallelism in the README.

# Changed Behaviour

N/A

# Fixes

N/A

## Type of change

Choose which options apply, and delete the ones which do not apply.

- Update to human readable text: Documentation/error messages/comments

### CODE REVIEW

**Comment by benclifford** [comment]
This failed because of a possibly unrelated possibly one off failure - it would be good if you could grab that whole failure into a separate issue to track down later before rerunning these tests.

**Comment by benclifford** [comment]
The background I come from this maybe would be phrased more as concurrent rather than parallel (which in my head comes more with the implication of closely synchronized MPI style code)

**Comment by WardLT** [comment]
The failure has been happening since Friday afternoon in all my branches. I think it's stemming from a bug in RADICAL Pilot

**Comment by WardLT** [comment]
I do like "concurrent" better, and that's what Python calls their `concurrent.futures` module anyway.

**Comment by benclifford** [comment]
> The failure has been happening since Friday afternoon in all my branches. I think it's stemming from a bug in RADICAL Pilot

Probably even more reason to open an issue, then

**Comment by benclifford** [comment]
see https://github.com/Parsl/parsl/issues/3429 for broken CI issue

**Review by benclifford — APPROVED** [review]

**Pull request merged**
