### PR TITLE
Add python 3.10, drop python 3.6

### PR DESCRIPTION
**Pull request by benclifford**
# Description
Python 3.10 was released 2021-10-04  (see https://www.python.org/dev/peps/pep-0619/)
Python 3.6 was end-of-lifed 2021-12-23 (see https://www.python.org/dev/peps/pep-0494/#lifespan)

## Type of change

- Code maintentance/cleanup

### CODE REVIEW

**Comment by benclifford** [comment]
as is usual with python upgrades for parsl, this is failing with pytest internals. I'll make a separate PR to upgrade pytest, which has been bothering me for other uses too.

**Comment by benclifford** [comment]
see #2209 for a pytest update that should merge before further work on this PR

**Comment by benclifford** [comment]
This PR has passed all 4 tests required by the branch: 3.7 .. 3.10, but github is configured to note that it is missing a 3.6 test - which it deliberately is.

**Review by yadudoc — APPROVED** [review]
This is reasonable. We should make a note of this in the announcement for next release.

**Pull request merged**
