### PR TITLE
Use incluster config fallback for KubernetesProvider

### PR DESCRIPTION
**Pull request by trey-stafford**
# Description

This PR supersedes https://github.com/Parsl/parsl/pull/2503

See https://github.com/kubernetes-client/python/issues/1005 for a good description of the issue.  

# Changed Behaviour

The `KubernetesProvider` now falls back to loading config in-cluster if a kube-config file is not found. This allows in-cluster submission of parsl jobs.

# Fixes

Fixes # (issue)

## Type of change

Choose which options apply, and delete the ones which do not apply.

- Bug fix

### CODE REVIEW

**Comment by benclifford** [comment]
some exciting new build problem with radical's build/packaging. I tried briefly to recreate it on my laptop and did not have a problem, so I'll dig into it more deeply later in the week - I'm not working on Parsl today.

**Comment by benclifford** [comment]
(very possibly related to build system changes in Python 3.12 which were/are fairly aggressive)

**Comment by mfisher87** [comment]
Oof. Thanks so much for providing that context and saving us from spinning our wheels on this! :heart:

**Comment by trey-stafford** [comment]
@benclifford I've merged in master. Happy to do that again as needed!

Note that I also amended my first commit to this PR to properly credit @manning-ncsa for work contributed in the superseded PR, #2503 .

**Comment by mfisher87** [comment]
@trey-stafford if you edit this PR can you enable "Allow maintainers to push"? Or is that only settable when opening the original PR? :thinking:

**Comment by benclifford** [comment]
you did something weird perhaps with rebase that makes the diff look weird - I think I know what, and I think that will fix itself once master gets merged again - which is necessary for putting this PR on master anyway as our tests require the PR be up to date.

**Comment by mfisher87** [comment]
I think I see what happened, we'll get it sorted on Monday!

**Comment by mfisher87** [comment]
:rocket: Sorry didn't get this done on Monday, but I think we're all fixed up now :)

**Review by benclifford — APPROVED** [review]

**Comment by benclifford** [comment]
Can you comment a bit on what the exception reported to a user looks like? Say the user intends to do something with the  config loaded by load_kube_config() but they mess it up in some way that raises an exception... does useful debugging information then get lost because that exception is immediately discarded?

**Comment by mfisher87** [comment]
I have a couple meetings coming up to prepare for but we will get back to you shortly!

**Comment by mfisher87** [comment]
Would you like that context in the commit message for this commit? 4833fc2f46f700a972bf45e57c94b595825f978f

**Comment by benclifford** [comment]
It doesn't really matter where you write it - if you have something really interesting to say, a comment in the code would be ok too, for example. Just more interested that someone thinks about it because I am always suspicious of too-easily-discarded exceptions.

**Comment by mfisher87** [comment]
We pushed another change that we feel will help prevent a really confusing user experience if both local config and incluster config fail to load. We used an ExceptionGroup to handle this, but perhaps the better solution is to only re-raise the local config exception with a note that we tried both loading local and incluster config. The ExceptionGroup looks like this when raised:

```
Traceback (most recent call last):
  File "/home/mfisher/Projects/qgreenland-net/parsl-exploration/src/parsl/parsl/providers/kubernetes/kube.py", line 109, in __init__
    config.load_kube_config()
  File "/home/mfisher/.miniconda3/envs/parsl-exploration/lib/python3.12/site-packages/kubernetes/config/kube_config.py", line 815, in load_kube_config
    loader = _get_kube_config_loader(
             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mfisher/.miniconda3/envs/parsl-exploration/lib/python3.12/site-packages/kubernetes/config/kube_config.py", line 772, in _get_kube_config_loader
    raise ConfigException(
kubernetes.config.config_exception.ConfigException: Invalid kube-config file. No configuration found.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/mfisher/Projects/qgreenland-net/parsl-exploration/src/parsl/parsl/providers/kubernetes/kube.py", line 123, in __init__
    config.load_incluster_config()
  File "/home/mfisher/.miniconda3/envs/parsl-exploration/lib/python3.12/site-packages/kubernetes/config/incluster_config.py", line 121, in load_incluster_config
    try_refresh_token=try_refresh_token).load_and_set(client_configuration)
                                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mfisher/.miniconda3/envs/parsl-exploration/lib/python3.12/site-packages/kubernetes/config/incluster_config.py", line 54, in load_and_set
    self._load_config()
  File "/home/mfisher/.miniconda3/envs/parsl-exploration/lib/python3.12/site-packages/kubernetes/config/incluster_config.py", line 62, in _load_config
    raise ConfigException("Service host/port is not set.")
kubernetes.config.config_exception.ConfigException: Service host/port is not set.

During handling of the above exception, another exception occurred:

  + Exception Group Traceback (most recent call last):
  |   File "/home/mfisher/Projects/qgreenland-net/parsl-exploration/run.py", line 104, in <module>
  |     config = get_parsl_config()
  |              ^^^^^^^^^^^^^^^^^^
  |   File "/home/mfisher/Projects/qgreenland-net/parsl-exploration/run.py", line 49, in get_parsl_config
  |     provider=KubernetesProvider(
  |              ^^^^^^^^^^^^^^^^^^^
  |   File "/home/mfisher/Projects/qgreenland-net/parsl-exploration/src/parsl/parsl/providers/kubernetes/kube.py", line 125, in __init__
  |     raise ExceptionGroup(
  | ExceptionGroup: Encountered errors loading kubernetes cluster configuration (2 sub-exceptions)
  +-+---------------- 1 ----------------
    | Traceback (most recent call last):
    |   File "/home/mfisher/Projects/qgreenland-net/parsl-exploration/src/parsl/parsl/providers/kubernetes/kube.py", line 109, in __init__
    |     config.load_kube_config()
    |   File "/home/mfisher/.miniconda3/envs/parsl-exploration/lib/python3.12/site-packages/kubernetes/config/kube_config.py", line 815, in load_kube_config
    |     loader = _get_kube_config_loader(
    |              ^^^^^^^^^^^^^^^^^^^^^^^^
    |   File "/home/mfisher/.miniconda3/envs/parsl-exploration/lib/python3.12/site-packages/kubernetes/config/kube_config.py", line 772, in _get_kube_config_loader
    |     raise ConfigException(
    | kubernetes.config.config_exception.ConfigException: Invalid kube-config file. No configuration found.
    +---------------- 2 ----------------
    | Traceback (most recent call last):
    |   File "/home/mfisher/Projects/qgreenland-net/parsl-exploration/src/parsl/parsl/providers/kubernetes/kube.py", line 123, in __init__
    |     config.load_incluster_config()
    |   File "/home/mfisher/.miniconda3/envs/parsl-exploration/lib/python3.12/site-packages/kubernetes/config/incluster_config.py", line 121, in load_incluster_config
    |     try_refresh_token=try_refresh_token).load_and_set(client_configuration)
    |                                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |   File "/home/mfisher/.miniconda3/envs/parsl-exploration/lib/python3.12/site-packages/kubernetes/config/incluster_config.py", line 54, in load_and_set
    |     self._load_config()
    |   File "/home/mfisher/.miniconda3/envs/parsl-exploration/lib/python3.12/site-packages/kubernetes/config/incluster_config.py", line 62, in _load_config
    |     raise ConfigException("Service host/port is not set.")
    | kubernetes.config.config_exception.ConfigException: Service host/port is not set.
    +------------------------------------
```

And as we're tying this @trey-stafford called out that `parsl` needs to support 3.10, and ExceptionGroups are new in 3.11.

**Comment by mfisher87** [comment]
@benclifford we think we've got things ready to go!

**Comment by benclifford** [comment]
ok cool. you still need to do something to let me update this branch, to fit in our merge process

**Comment by benclifford** [comment]
wrt your comment on using Python 3.11 features, in recent years our informal policy has been to support the same Python versions as are listed here as "bugfix" or "security", so under that model, no 3.11 features until near the end of 2026 - https://devguide.python.org/versions/

We have a low-key project going on to understand our usage a bit better, and my gut feeling is that with people using things like `conda` more and being less tied to system-level Python, we could probably drop support earlier (and so access newer features like ExceptionGroups earlier) - tagging @NishchayKarle who is working on that usage project to help him understand this use case for that work.

**Comment by mfisher87** [comment]
>ok cool. you still need to do something to let me update this branch, to fit in our merge process

Shoot. I think @trey-stafford has to do that, and he may not be available until Monday. I don't have an edit button even though the PR is from a repo I have write access to. As ugly as it is, I can create another fork and open a new PR and ensure the "allow maintainers to change" checkbox is ticket if you'd like to get this merged sooner than that.

**Comment by benclifford** [comment]
@mfisher87 no super rush to mess around to get it merged

**Comment by trey-stafford** [comment]
> > ok cool. you still need to do something to let me update this branch, to fit in our merge process
> 
> Shoot. I think @trey-stafford has to do that, and he may not be available until Monday. I don't have an edit button even though the PR is from a repo I have write access to. As ugly as it is, I can create another fork and open a new PR and ensure the "allow maintainers to change" checkbox is ticket if you'd like to get this merged sooner than that.
> 
> Trey, when you get to it, this checkbox is towards the bottom of the right sidebar:
> 
> image

This option is not available. I think it's because this is an org-forked repo. [This documentation](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork) suggests it is possible with "user-owned forks". 

Maybe a new fork is the right path?

**Comment by trey-stafford** [comment]
Ok, I transferred the repo to my personal account and was able to enable edits and access by maintainers! @benclifford hopefully that does the trick!

**Comment by mfisher87** [comment]
Did it turn out that the setting was not available because we forked to an org?

In retrospect, that makes sense, as checking that box would give maintainers of other projects access to _org-wide_ secrets! :exploding_head:

**Comment by benclifford** [comment]
ok that worked, so this will be in the next Parsl release happening in the next few hours. Thanks!

**Comment by sophie-bui** [comment]
👋 Hi @trey-stafford and @mfisher87! My name is Sophie and I'm Parsl's community manager.

We're trying to broadly understand how people are using Parsl and would appreciate it if either/both of you would fill out our quick survey: [https://bit.ly/parsl-use-survey](https://bit.ly/parsl-use-survey). Thanks in advance!

**Comment by mfisher87** [comment]
Hey @sophie-bui thanks for asking for our input! I just filled it out.

**Pull request merged**
