### PR TITLE
Include requirements.txt in pip package to enable building from source

### PR DESCRIPTION
**Pull request by jan-janssen**
# Description

Include requirements.txt in pip package to enable building from source

Fixes # (issue)
https://github.com/conda-forge/parsl-feedstock/pull/9

## Type of change

Choose which options apply, and delete the ones which do not apply.

- [x] Bug fix (non-breaking change that fixes an issue)
- [ ] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update
- [ ] Code maintentance/cleanup

### CODE REVIEW

**Review by benclifford — APPROVED** [review]

**Comment by benclifford** [comment]
Hi! thanks for this @jan-janssen

**Comment by jan-janssen** [comment]
@benclifford Is it possible to release a new version on `pypi`? The issue is that so far conda-forge used the GitHub tags, but as those were no longer updated the version of `parsl` on conda-forge is outdated as well. One approach to address this would be to fix the pip package so conda-forge can build it from source, as I suggested here. Another approach would be to add GitHub tags again which are consistent with the pypi package releases. https://github.com/conda-forge/parsl-feedstock/pulls

**Comment by benclifford** [comment]
pinging @yadudoc who did the automated release work. If you wait until Monday, a new version will get autoreleased onto pypi, using a current master.

cross-ref https://github.com/Parsl/parsl/issues/2451 which requests git tags for automatic releases

**Comment by jan-janssen** [comment]
> If you wait until Monday, a new version will get autoreleased onto pypi, using a current master.

Monday is fine for me - thanks

**Pull request merged**
