### PR TITLE
Implement a method to summarise all DFK tasks; and call it at shutdown

### PR DESCRIPTION
**Pull request by benclifford**
This has been useful when debugging hangs.

I'm not sure if it belongs on `master`, or if it should be optional. I can imagine it getting very big on runs with lots of tasks.

### CODE REVIEW

**Comment by annawoodard** [comment]
I think this is really useful, and should be merged. I favor changing the logging level to `DEBUG` rather than adding an extra knob to turn it on or off.

We might consider this, which would be more compact for big runs:
```
2018-06-05 09:35:23 parsl.dataflow.dflow:572 [DEBUG] Task IDs in DFK which are done: 3
2018-06-05 09:35:23 parsl.dataflow.dflow:572 [DEBUG] Task IDs in DFK which are running: 1, 2, 3, 4, 5
```
over this:
```
2018-06-05 09:35:23 parsl.dataflow.dflow:572 [INFO]  List of tasks in DFK: 
(0=Pending, 2=Running, 3=Done, 4=Failed, 5=Dep failed)
2018-06-05 09:35:23 parsl.dataflow.dflow:574 [INFO]  Task tid 0 status 3
2018-06-05 09:35:23 parsl.dataflow.dflow:574 [INFO]  Task tid 1 status 2
2018-06-05 09:35:23 parsl.dataflow.dflow:574 [INFO]  Task tid 2 status 2
2018-06-05 09:35:23 parsl.dataflow.dflow:574 [INFO]  Task tid 3 status 2
2018-06-05 09:35:23 parsl.dataflow.dflow:574 [INFO]  Task tid 4 status 2
2018-06-05 09:35:23 parsl.dataflow.dflow:574 [INFO]  Task tid 5 status 2
```

**Comment by annawoodard** [comment]
Thinking about it more, I agree it should be `INFO` rather than `DEBUG`. I don't think we need a knob to turn it on or off, especially in the compact form.

**Comment by annawoodard** [comment]
(note I just made a minor edit to the proposal above)

**Comment by benclifford** [comment]
This PR now outputs in this format:

```
2018-06-12 09:51:35 parsl.dataflow.dflow:629 [INFO]  DFK cleanup initiated
2018-06-12 09:51:35 parsl.dataflow.dflow:575 [INFO]  Summary of tasks in DFK:
2018-06-12 09:51:35 parsl.dataflow.dflow:606 [INFO]  Tasks in state States.failed: 0, 1, 2
2018-06-12 09:51:35 parsl.dataflow.dflow:606 [INFO]  Tasks in state States.dep_fail: 3
2018-06-12 09:51:35 parsl.dataflow.dflow:613 [INFO]  End of summary
...
```

**Pull request merged**
