### PR TITLE
Cluster provider

### LINKED ISSUE #3234: parsl.providers.cluster_provider _write_submit_script should return nothing, rather than constant True
**Describe the bug**

_write_submit_script in parsl.providers.cluster_provider indicates failure by raising an exception, and so should not be returning a True (or False) value. Instead it should return None by either `return` on its own, or falling off the end of the method without a return statement.

To tidy this up, change that return handling. Edit the docstring to match.

### PR DESCRIPTION
**Pull request by MundiaNderi**
# Description

The cluster provider indicates failure by raising an exception, and so should not be returning a True (or False) value.

# Changed Behaviour

It should return None or raise an exception.

# Fixes

Fixes #3234

## Type of change

- Bug fix

### CODE REVIEW

**Comment by MundiaNderi** [comment]
@benclifford kindly give me your input. I'm cleaning my PRs up such as this one to only have one issue per PR. This PR has 9 commits, some unrelated to this issue.

For other outreachy issues, I run this process and it worked:
- git rebase -i HEAD~n which lists all commits
- drop this commit that doesn't apply to this PR/issue/branch.
- pick this commit that applies to the issue/PR .
- git rebase
- git force push

I tried it with this branch and it picked up other people's PRs and had conflicts. So because the branch is behind I merged master into cluster_provider which doesn't sound like a great choice now as I'm typing.

Tried to edit the branch but I still have conflicts and PRs not belonging to this branch which I would not want to interfere with. What would be the best way to resolve this? Thank you.

**Comment by benclifford** [comment]
Probably for a small change like you are trying to make here, I would start with a very clean branch off the main parsl `master` branch, make a new branch from that (named after what you are trying to change, or an issue number, or something like that), and then make your change there.

I think using rebase and force push can get you into all sorts of tangles that are hard to resolve.

**Comment by khk-globus** [comment]
Hi @MundiaNderi,

To briefly chime in here, I think there are a couple of concepts in play.  Certainly, @benclifford has highlighted a key methodology that is important to understand: 1 feature per pull request (so 1 feature per branch).  That's a big deal, especially when it comes to a fellow human precisely understanding the PR's proposed modifications.  One big aspect of PRs is communication with other humans, so keeping their scope focused is important.

The other concept is the idea of rebasing vs merging.  I'll not discuss those in detail but mention that they don't play well together.  In particular, once you merge in from master, the Git history of the branch is _different_ that had you rebased, and that prevents further rebasing.  I'll leave the research of _why_ this is the case to you (as, for one thing, there are many articles on the internet that will do a better job than I can do at explaining).

But as to your specific process, _after_ you've researched and understand the difference between merging and rebasing, I'll observe that I think you don't want `git rebase -i HEAD~n`, but rather

- `git rebase master`, or
- `git rebase -i master`

**Comment by MundiaNderi** [comment]
Thank you @benclifford @khk-globus . This is my first time working with Open source/ PRs and I'm learning a lot, albeit with mistakes here and there. I'll be sure to read up on merging and rebasing and refer to this thread when I get lost.

**Pull request closed without merging**
