### PR TITLE
ENH scale in a lot

### PR DESCRIPTION
**Pull request by beckermr**
# Description

Please include a summary of the change and (optionally) which issue is fixed. Please also include
relevant motivation and context.

Fixes # (issue)

## Type of change

Choose which options apply, and delete the ones which do not apply.

- Bug fix (non-breaking change that fixes an issue)
- New feature (non-breaking change that adds functionality)
- Breaking change (fix or feature that would cause existing functionality to not work as expected)
- Documentation update
- Code maintentance/cleanup

### CODE REVIEW

**Comment by beckermr** [comment]
I'm try this out since the scale down appears to stall when it scaled up too much for my condor jobs.

**Comment by beckermr** [comment]
So this doesn't help as much as I'd like because blocks started with managers that never phone-home are not considered when scaling down. Idle blocks that are queued but not running are not considered either when scaling down.

**Comment by beckermr** [comment]
I think that is related to #2171

**Comment by benclifford** [comment]
> I think that is related to #2171

yep I think so

**Comment by benclifford** [comment]
> blocks started with managers that never phone-home are not considered when scaling down. Idle blocks that are queued but not running are not considered either when scaling down.

Both of those cases are hitting the same wrong code path: high throughput executor forms a block list by looking at which managers have registered.

**Comment by beckermr** [comment]
One question I have is why jobs on my local condor system with failed managers are not failing. Or maybe they are and I don't know it?

**Comment by beckermr** [comment]
One more issue here is that jobs are not eligible to be killed if they have not started. So when an executor has less tasks than blocks, it should go back and cancel any jobs it has queued.

**Comment by beckermr** [comment]
We think we are seeing jobs linger but it is hard to construct a good test case.

**Comment by yadudoc** [comment]
Can you get a paste of the `condor_q <JOB_ID>` on some of the failing tasks, please? Debugging might go quicker if we could connect over slack. There's a slack invite link on this page, if you're not already on parsl slack (http://parsl-project.org/support.html).

**Comment by beckermr** [comment]
I am trying to get debugging data together but it is not so easy. let me get back to you.

**Comment by beckermr** [comment]
I sent a run with failed managers over slack. Hopefully this helps.

**Comment by beckermr** [comment]
I did a bunch more checking. I think the main thing here is that scaling in ignores pilot jobs which have been submitted but are not running and are not needed and it ignores jobs where the manager never connected. 

I can confirm that jobs with managers that cannot connect are ending eventually. However, those jobs may end after the main parsl script finishes since there is a 2 minute delay and the main parsl script doesn't remove pending jobs as it completes. 

Thus I think the main changes needed here (some of which @yadudoc is already working on) are to:

1. kill/rm all provider jobs when parsl is exiting.
2. enable the scale_in code to consider jobs other than those which are connected. In fact, it makes more sense when scaling in to remove submitted jobs that are not yet running (instead of letting them boot up to simply exit later).

**Comment by yadudoc** [comment]
Right, so this is good. Managers are exiting even when parsl does a dirty exit. Hoewever, due to some oddities with condor and our use of the option `leave_in_queue=True` the jobs become orphaned and linger. The proper fix for that, as you note is for parsl to cleanup and cancel all jobs including pending ones on exit. I've got some untested changes over here -> https://github.com/Parsl/parsl/tree/cancel_pending_jobs_on_shutdown . I'm waiting for an account on a condor based system to test these out.

**Comment by beckermr** [comment]
I can test them later today from your branch. 

Do you have comments on 2 above? Is there a way for us to query the provider to get jobs that have not yet started and proactively remove those as things scale in?

**Comment by yadudoc** [comment]
Good question. During the run, we have jobs that are running tasks, idling, and pending. We can assume that we call scale_in when 1) there's excess capacity 2) we are shutting down. In case of excess capacity, you're right that we probably should cancel the pending jobs. I believe the simplest mechanism for this would be to tweak the order in which blocks are canceled in `HighThroughputExecutor.scale_in()`.

**Comment by beckermr** [comment]
bugz in your branch:

```
Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "/gpfs/mnt/gpfs02/astro/workarea/beckermr/misc/work/parsl_condor/test-parsl-version/parsl/parsl/dataflow/dflow.py", line 1023, in atexit_cleanup
    self.cleanup()
  File "/gpfs/mnt/gpfs02/astro/workarea/beckermr/misc/work/parsl_condor/test-parsl-version/parsl/parsl/dataflow/dflow.py", line 1088, in cleanup
    block_ids = executor.scale_in(len(job_ids), max_idletime=0, force=True)
  File "/gpfs/mnt/gpfs02/astro/workarea/beckermr/misc/work/parsl_condor/test-parsl-version/parsl/parsl/executors/high_throughput/executor.py", line 648, in scale_in
    block_info[b_id].task_count += manager['tasks']
TypeError: unsupported operand type(s) for +=: 'property' and 'int'
```

**Comment by yadudoc** [comment]
@beckermr Could you try again, please? I've made some changes.

**Comment by beckermr** [comment]
Error is gone but I still see jobs running ~5 minutes after the parsl job is done:

```
Jobs: 1000 Running: 20 Reserved: 0 Idle: 0 Removed: 487 Completed: 493 

 ID        Owner     Submitted       Run Time    ST  Pri  Size   Cmd   Host
 152673.0  beckermr  12/08 16:37:28  0+00:16:41  R   0    976.6  bash  slot1_43@spool0682
 152893.0  beckermr  12/08 16:37:43  0+00:13:25  R   0    976.6  bash  slot1_19@spool0682
 152914.0  beckermr  12/08 16:37:45  0+00:13:25  R   0    976.6  bash  slot1_20@spool0682
 152916.0  beckermr  12/08 16:37:45  0+00:13:23  R   0    976.6  bash  slot1_36@spool0682
 152918.0  beckermr  12/08 16:37:45  0+00:13:23  R   0    976.6  bash  slot1_52@spool0682
 152926.0  beckermr  12/08 16:37:45  0+00:12:52  R   0    976.6  bash  slot1_43@spool0680
 152947.0  beckermr  12/08 16:37:47  0+00:12:51  R   0    976.6  bash  slot1_46@spool0680
 152958.0  beckermr  12/08 16:37:47  0+00:12:24  R   0    976.6  bash  slot1_10@spool0682
 153085.0  beckermr  12/08 16:37:55  0+00:07:10  R   0    976.6  bash  slot1_15@spool0682
 153092.0  beckermr  12/08 16:37:55  0+00:07:10  R   0    976.6  bash  slot1_59@spool0682
 153101.0  beckermr  12/08 16:37:56  0+00:06:39  R   0    976.6  bash  slot1_19@spool0680
 153114.0  beckermr  12/08 16:37:57  0+00:06:39  R   0    976.6  bash  slot1_50@spool0680
 153500.0  beckermr  12/08 16:38:21  0+00:04:23  R   0    976.6  bash  slot1_44@spool0870
 153501.0  beckermr  12/08 16:38:21  0+00:04:23  R   0    976.6  bash  slot1_46@spool0870
 153502.0  beckermr  12/08 16:38:21  0+00:04:23  R   0    976.6  bash  slot1_70@spool0870
 153504.0  beckermr  12/08 16:38:21  0+00:04:23  R   0    976.6  bash  slot1_87@spool0870
 153505.0  beckermr  12/08 16:38:21  0+00:04:23  R   0    976.6  bash  slot1_40@spool0870
 153506.0  beckermr  12/08 16:38:21  0+00:04:23  R   0    976.6  bash  slot1_55@spool0870
 153511.0  beckermr  12/08 16:38:21  0+00:04:23  R   0    976.6  bash  slot1_41@spool0870
 153517.0  beckermr  12/08 16:38:22  0+00:04:22  R   0    976.6  bash  slot1_61@spool0870 
```

**Pull request closed without merging**
