### PR TITLE
Expose task state as a method of AppFuture

### PR DESCRIPTION
**Pull request by benclifford**
Partly addresses #103 - it exposes the task state
to end uses via the AppFuture interface; but the
task state is not particularly rich information.

### CODE REVIEW

**Comment by yadudoc** [comment]
@benclifford and I had a chat about this and decided that it would be useful to have a broader discussion of what states might be useful to expose to the user that we already can tease out from the DFK. In addition we also need to consider the perf cost of fine grained state reporting from the new executors.

**Comment by benclifford** [comment]
Another thing I was wondering is what people want to do with more exposed/interesting state: if it is something like log it to a console / group it by identical states, then we could return a string and have great flexibility in how we proceed; if we're trying to do something with more structured data, there's a rathole of data structure design/backward compatibility constraints to fall down.

**Comment by benclifford** [comment]
I think this feature is worth revisiting soonish, in the context of the richer information now available (sometimes) in the monitoring DB. One view is that this call would give a view into the relevant part of the monitoring DB information.

**Comment by yadudoc** [comment]
@benclifford What do we want to do about this. I'm okay with merging this, the code is fine. As covered in the discussion we do not yet have the richer state info that might be in the monitoring db available yet in the dfk side.

**Pull request merged**
