### PR TITLE
WQ coprocess: generate parsl_coprocess.py at runtime

### LINKED ISSUE #2914: Newly frequent WorkQueueTaskFailure in CI
**Describe the bug**

I'm seeing this WorkQueueExecutor heisenbug happen in CI a lot recently: I'm not clear what has changed to make it happen more - for example in https://github.com/Parsl/parsl/actions/runs/6518865549/job/17704749713

```
ERROR    parsl.dataflow.dflow:dflow.py:350 Task 207 failed after 0 retry attempts
Traceback (most recent call last):
  File "/home/runner/work/parsl/parsl/parsl/dataflow/dflow.py", line 301, in handle_exec_update
    res = self._unwrap_remote_exception_wrapper(future)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/work/parsl/parsl/parsl/dataflow/dflow.py", line 571, in _unwrap_remote_exception_wrapper
    result = future.result()
             ^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.11.5/x64/lib/python3.11/concurrent/futures/_base.py", line 449, in result
    return self.__get_result()
           ^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.11.5/x64/lib/python3.11/concurrent/futures/_base.py", line 401, in __get_result
    raise self._exception
parsl.executors.workqueue.errors.WorkQueueTaskFailure: ('work queue result: The result file was not transfered from the worker.\nThis usually means that there is a problem with the python setup,\nor the wrapper that executes the function.\nTrace:\n', FileNotFoundError(2, 'No such file or directory'))
INFO     parsl.dataflow.dflow:dflow.py:1390 Standard output for task 207 available at std.out
```

I'm don't have any immediate strong ideas about what is going on - I've had a little poke but can't see anything that sticks out right away.

I've opened:
* PR #2912 to try a newer cctools
* draft PR #2910 to try to capture more FileNotFoundError information in output - there is more stuff in that FileNotFoundError (such as the actual filename) that isn't rendered by the above error reporting

I haven't been successful in recreating this on my laptop. However I have seen a related error on perlmutter under certain high load / high concurrency conditions which is a bit more recreatable and maybe I can debug from there.

cc @dthain

### PR DESCRIPTION
**Pull request by colinthomas-z80**
# Description
Generate parsl_coprocess.py at runtime.

A more pragmatic solution for #2914 which was temporarily fixed by #2977, where the generation of this file remained a manual process. Now it will be generated by the current version of ndcctools. 

# Changed Behaviour

Using work queue coprocess will put parsl_coprocess.py in the user's directory at runtime. If there are better suggestions of where to store it I am open to them.

# Fixes

#2914

## Type of change

- Code maintenance/cleanup

### CODE REVIEW

**Comment by benclifford** [comment]
ok I like this approach better. I had imagined it happening as part of the `pip` install procedure but the way its done in this PR seems fine too, I think.

Directorywise, maybe the right place is inside the particular executor instances working directory (alongside, for example, `"function_data"` ?

eg.
            self.function_data_dir = os.path.join(self.run_dir, self.label, "function_data")

**Comment by benclifford** [comment]
this failed on a couple of CI tests with:

```
parsl.executors.errors.ExecutorError: Executor WorkQueueExecutor failed due to: Workqueue Submit Process is not alive
```

and digging into the downloadable logs:

```
1706718555.814392 2024-01-31 16:29:15 WorkQueue-Submit-Process-7549 MainThread-139731849144128 parsl.process_loggers:31 wrapped ERROR: Exceptional ending for _work_queue_submit_wait on thread MainThread
Traceback (most recent call last):
  File "/home/runner/work/parsl/parsl/parsl/process_loggers.py", line 27, in wrapped
    r = func(*args, **kwargs)
  File "/home/runner/work/parsl/parsl/parsl/executors/workqueue/executor.py", line 846, in _work_queue_submit_wait
    from ndcctools.poncho import package_serverize
  File "/tmp/cctools/lib/python3.8/site-packages/ndcctools/poncho/package_serverize.py", line 9, in <module>
    from ndcctools.poncho import package_create as create
  File "/tmp/cctools/lib/python3.8/site-packages/ndcctools/poncho/package_create.py", line 13, in <module>
    import conda_pack
ModuleNotFoundError: No module named 'conda_pack'
```

which I guess is a dependency problem...

**Comment by colinthomas-z80** [comment]
conda-pack appears to be listed as a dependency in the parsl-workqueue documentation.

Would this be as simple as adding a "pip install conda-pack" in install-workqueue.sh ?

**Comment by benclifford** [comment]
I noticed a problem to be aware of perhaps when upgrading from an earlier parsl: when I re-installed parsl in my dev env from your branch, it did not remove all traces of the old parsl_coprocess.py script, so I ended up with hanging work_queue_worker processes that when I ran them manually showed this:

```$ work_queue_worker --coprocess parsl_coprocess.py parsl-dev-3-11-3926 9000
work_queue_worker: creating workspace /tmp/worker-1000-104
work_queue_worker: using 4 cores, 15704 MB memory, 539 MB disk, 0 gpus
Traceback (most recent call last):
  File "/home/benc/parsl/virtualenv-3.11/bin/parsl_coprocess.py", line 6, in <module>
    with open(__file__) as f:
         ^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/home/benc/parsl/src/parsl/parsl/executors/workqueue/parsl_coprocess.py'
```

**Comment by benclifford** [comment]
now in CI, I see this:

```
parsl.executors.errors.BadStateException: Executor WorkQueueExecutor failed due to: Error 1:
	EXIT CODE: 143
	STDOUT: Found cores : 4
Launching worker: 1

	STDERR: 2024/01/31 18:42:41.67 work_queue_worker[7954] fatal: could not resolve path `parsl_coprocess.py': No such file or directory
Terminated
```

which I guess is the paths not being set right to point to where this PR puts parsl_coprocess.py. In a shared-fs environment, I'd suggest using a full path here, but I'm not sure what that looks like when WQ is in a non-shared fs environment.

**Comment by benclifford** [comment]
(before this PR, the install script put parsl_coprocess.py in the virtualenv bin directory, which is added to $PATH when you activate the virtualenv)

**Comment by colinthomas-z80** [comment]
Right. So I can copy it into a shared location and it works, but now it is not packaged with the worker environment for non-shared fs runs... hmm

**Comment by colinthomas-z80** [comment]
I do not think there is a good opportunity for us to generate the file at runtime and get it to the worker before it starts. I wish to turn my attention to the install script to see if it may be generated there so it may be included in the venv

**Comment by benclifford** [comment]
> I do not think there is a good opportunity for us to generate the file at runtime and get it to the worker before it starts. I wish to turn my attention to the install script to see if it may be generated there so it may be included in the venv

ok. I don't really have any experience in that sort of Python build/packaging - I had a look a few months ago very briefly with this in mind but I didn't come up with anything. So I'm probably not going to be much help here.

**Pull request closed without merging**
