### PR TITLE
Added QuarkNet's NSF award number

### PR DESCRIPTION
**Pull request by JG-QuarkNet**
# Description

Please include a summary of the change and (optionally) which issue is fixed. Please also include
relevant motivation and context.

Fixes # (issue)

## Type of change

Choose which options apply, and delete the ones which do not apply.

- Bug fix (non-breaking change that fixes an issue)
- New feature (non-breaking change that adds functionality)
- Breaking change (fix or feature that would cause existing functionality to not work as expected)
- Documentation update
- Code maintentance/cleanup

### CODE REVIEW

**Review by kylechard — COMMENTED** [review]
I think hte award number should be NSF- 1550476

**Comment by danielskatz** [comment]
Hi @JG-QuarkNet - the award number is actually 1550476

And you also need to add

```
.. |NSF-1550476 | image:: https://img.shields.io/badge/NSF-1550476-blue.svg
   :target: https://nsf.gov/awardsearch/showAward?AWD_ID= 1550476
   :alt: NSF award info
```

further down in the readme

**Comment by JG-QuarkNet** [comment]
Did it wrong

**Comment by danielskatz** [comment]
no problem - for the future, you can continue to make changes to an existing PR, you don't need to delete it and then create a new one, but it doesn't matter too much at this point

**Pull request closed without merging**
