### PR TITLE
Fix htex scale down breakage due to overly aggressive result heartbeat

### PR DESCRIPTION
**Pull request by benclifford**
PR #2104 introduced a result channel heartbeat. However, this heartbeat
resulted in the idle time of managers being updated on each heartbeat.

Because of this, no manager ever appears to be idling for very long.

And because of this, the scale down code will not select any manager
for scaling down.

This PR makes result channel messages not update the idle time if
a manager already has an idle time: a result channel message (either
a result or a heartbeat) now means:
"I am (still) idle", rather than "I am idle starting from now".

There is no CI test for this (before or after). See issue #1885 

## Type of change

- Bug fix (non-breaking change that fixes an issue)

### CODE REVIEW

**Comment by benclifford** [comment]
Quentin Le Boulc'h has tested this fix applied to the `desc` branch and it fixed scaling down for his 1200 block run.

**Comment by benclifford** [comment]
cc @jrueb  - does this change make sense to you?

**Comment by jrueb** [comment]
Looks good to me.

**Review by yadudoc — APPROVED** [review]
This looks correct.

**Pull request merged**
