### PR TITLE
Remove unused RESOURCE_INFO message tag

### PR DESCRIPTION
**Pull request by benclifford**
Resource messages are delivered via their own queue
and do not need a tag.

### CODE REVIEW

**Comment by ZhuozhaoLi** [comment]
Probably a more appropriate fix would be changing `TASK_INFO` in the line below to `RESOURCE_INFO` (that was a typo). 
https://github.com/Parsl/parsl/blob/aa545d7f38c6a7b6654b61c8f81ab59487bf2d5b/parsl/monitoring/monitoring.py#L561

I am fine with totally remove `RESOURCE_INFO`---this kind of messages are not specifically checked in `db_manager` because these messages come from a separate queue. But I was wondering if it would be useful to keep this `RESOURCE_INFO` tag in case we need to check it in the future.

**Comment by benclifford** [comment]
That message type parameter never gets used for anything: message routing happens in a different way.

We should only keep unused code around if there is a clear reason for it.

**Comment by ZhuozhaoLi** [comment]
> That message type parameter never gets used for anything: message routing happens in a different way.
> 
> We should only keep unused code around if there is a clear reason for it.

We may want to remove UDP and use only one ZMQ channel in the Hub (router) in the future. In that case, it would be useful to check the message type there, no? Or adding it back when we actually switch would be better.

**Comment by benclifford** [comment]
> adding it back when we actually switch would be better.

this. but *if*, not *when*

**Pull request merged**
